"""
All Indian crop disease names in 10 languages.
Keys = canonical class names from training.
"""

# language codes: en, hi, mr, kn, te, ta, bn, gu, pa, ur

DISEASE_TRANSLATIONS = {
    "Tomato_Early_Blight": {
        "en": "Tomato Early Blight",
        "hi": "टमाटर अगेती झुलसा रोग",
        "mr": "टोमॅटो अर्ली ब्लाइट",
        "kn": "ಟೊಮೇಟೋ ಅರ್ಲಿ ಬ್ಲೈಟ್",
        "te": "టమాటా తొలి ముడత వ్యాధి",
        "ta": "தக்காளி ஆரம்ப கருகல் நோய்",
        "bn": "টমেটো আর্লি ব্লাইট",
        "gu": "ટામેટા અર્લી બ્લાઈટ",
        "pa": "ਟਮਾਟਰ ਅਗੇਤੀ ਝੁਲਸ ਰੋਗ",
        "ur": "ٹماٹر کا جلدی جھلسا",
        "severity": "moderate",
        "treatment": "Apply chlorothalonil or mancozeb fungicide",
    },
    "Tomato_Late_Blight": {
        "en": "Tomato Late Blight",
        "hi": "टमाटर पछेती झुलसा रोग",
        "mr": "टोमॅटो लेट ब्लाइट",
        "kn": "ಟೊಮೇಟೋ ಲೇಟ್ ಬ್ಲೈಟ್",
        "te": "టమాటా ఆలస్య ముడత వ్యాధి",
        "ta": "தக்காளி தாமத கருகல் நோய்",
        "bn": "টমেটো লেট ব্লাইট",
        "gu": "ટામેટા લેટ બ્લાઈટ",
        "pa": "ਟਮਾਟਰ ਪਛੇਤੀ ਝੁਲਸ",
        "ur": "ٹماٹر کا دیر سے جھلسا",
        "severity": "high",
        "treatment": "Apply metalaxyl+mancozeb, remove infected plants",
    },
    "Tomato_Bacterial_Spot": {
        "en": "Tomato Bacterial Spot",
        "hi": "टमाटर जीवाणु धब्बा रोग",
        "mr": "टोमॅटो बॅक्टेरियल स्पॉट",
        "kn": "ಟೊಮೇಟೋ ಬ್ಯಾಕ್ಟೀರಿಯಲ್ ಸ್ಪಾಟ್",
        "te": "టమాటా బాక్టీరియల్ స్పాట్",
        "ta": "தக்காளி பாக்டீரியல் புள்ளி நோய்",
        "bn": "টমেটো ব্যাকটেরিয়াল স্পট",
        "gu": "ટામેટા બેક્ટેરિયલ સ્પૉટ",
        "pa": "ਟਮਾਟਰ ਬੈਕਟੀਰੀਅਲ ਧੱਬਾ",
        "ur": "ٹماٹر بیکٹیریائی دھبہ",
        "severity": "moderate",
        "treatment": "Copper-based bactericides, disease-free seeds",
    },
    "Tomato_Leaf_Mold": {
        "en": "Tomato Leaf Mold",
        "hi": "टमाटर पत्ती फफूंद",
        "mr": "टोमॅटो पानावरील बुरशी",
        "kn": "ಟೊಮೇಟೋ ಎಲೆ ಶಿಲೀಂಧ್ರ",
        "te": "టమాటా ఆకు అచ్చు",
        "ta": "தக்காளி இலை பூஞ்சை",
        "bn": "টমেটো পাতার ছাঁচ",
        "gu": "ટામેટા પાન ઘાટ",
        "pa": "ਟਮਾਟਰ ਪੱਤੀ ਉੱਲੀ",
        "ur": "ٹماٹر پتی پھپھوندی",
        "severity": "moderate",
        "treatment": "Improve ventilation, apply fungicide",
    },
    "Tomato_Septoria_Leaf_Spot": {
        "en": "Tomato Septoria Leaf Spot",
        "hi": "टमाटर सेप्टोरिया पत्ती धब्बा",
        "mr": "टोमॅटो सेप्टोरिया स्पॉट",
        "kn": "ಟೊಮೇಟೋ ಸೆಪ್ಟೋರಿಯಾ ಎಲೆ ಚುಕ್ಕೆ",
        "te": "టమాటా సెప్టోరియా ఆకు మచ్చ",
        "ta": "தக்காளி செப்டோரியா இலை புள்ளி",
        "bn": "টমেটো সেপ্টোরিয়া দাগ",
        "gu": "ટામેટા સેપ્ટોરિયા પાન ડાઘ",
        "pa": "ਟਮਾਟਰ ਸੈਪਟੋਰੀਆ ਧੱਬਾ",
        "ur": "ٹماٹر سیپٹوریا دھبہ",
        "severity": "moderate",
        "treatment": "Remove infected leaves, apply mancozeb",
    },
    "Tomato_Spider_Mites": {
        "en": "Tomato Spider Mites",
        "hi": "टमाटर मकड़ी कीट",
        "mr": "टोमॅटो स्पायडर माइट्स",
        "kn": "ಟೊಮೇಟೋ ಜೇಡ ಪಿಡುಗು",
        "te": "టమాటా సాలె పురుగు",
        "ta": "தக்காளி சிலந்தி பூச்சி",
        "bn": "টমেটো মাকড়",
        "gu": "ટામેટા કરોળિયા જીવાત",
        "pa": "ਟਮਾਟਰ ਮੱਕੜੀ ਕੀੜੇ",
        "ur": "ٹماٹر مکڑی",
        "severity": "high",
        "treatment": "Neem oil spray, miticides like abamectin",
    },
    "Tomato_Target_Spot": {
        "en": "Tomato Target Spot",
        "hi": "टमाटर लक्ष्य धब्बा",
        "mr": "टोमॅटो टार्गेट स्पॉट",
        "kn": "ಟೊಮೇಟೋ ಟಾರ್ಗೆಟ್ ಸ್ಪಾಟ್",
        "te": "టమాటా టార్గెట్ స్పాట్",
        "ta": "தக்காளி இலக்கு புள்ளி",
        "bn": "টমেটো টার্গেট স্পট",
        "gu": "ટામેટા ટાર્ગેટ સ્પૉટ",
        "pa": "ਟਮਾਟਰ ਟਾਰਗੈਟ ਧੱਬਾ",
        "ur": "ٹماٹر ٹارگٹ دھبہ",
        "severity": "moderate",
        "treatment": "Chlorothalonil or azoxystrobin fungicide",
    },
    "Tomato_Yellow_Leaf_Curl_Virus": {
        "en": "Tomato Yellow Leaf Curl Virus",
        "hi": "टमाटर पीला पत्ती कुंचन विषाणु रोग",
        "mr": "टोमॅटो येलो लीफ कर्ल व्हायरस",
        "kn": "ಟೊಮೇಟೋ ಹಳದಿ ಎಲೆ ಸುರುಳಿ ವೈರಸ್",
        "te": "టమాటా పసుపు ఆకు వంకర వైరస్",
        "ta": "தக்காளி மஞ்சள் இலை சுருள் வைரஸ்",
        "bn": "টমেটো হলুদ পাতা কোঁকড়া ভাইরাস",
        "gu": "ટામેટા પીળા પાન કર્ળ વાઇરસ",
        "pa": "ਟਮਾਟਰ ਪੀਲਾ ਪੱਤੀ ਕੁੰਚਣ",
        "ur": "ٹماٹر پیلا پتی وائرس",
        "severity": "high",
        "treatment": "Control whitefly vectors, use resistant varieties",
    },
    "Tomato_Mosaic_Virus": {
        "en": "Tomato Mosaic Virus",
        "hi": "टमाटर मोज़ेक विषाणु",
        "mr": "टोमॅटो मोझेक व्हायरस",
        "kn": "ಟೊಮೇಟೋ ಮೊಸಾಯ್ಕ್ ವೈರಸ್",
        "te": "టమాటా మొజాయిక్ వైరస్",
        "ta": "தக்காளி மொசைக் வைரஸ்",
        "bn": "টমেটো মোজাইক ভাইরাস",
        "gu": "ટામેટા મોઝેક વાઇરસ",
        "pa": "ਟਮਾਟਰ ਮੋਜ਼ੇਕ ਵਾਇਰਸ",
        "ur": "ٹماٹر موزیک وائرس",
        "severity": "high",
        "treatment": "Remove infected plants, sanitize tools",
    },
    "Tomato_Healthy": {
        "en": "Tomato — Healthy",
        "hi": "टमाटर — स्वस्थ",
        "mr": "टोमॅटो — निरोगी",
        "kn": "ಟೊಮೇಟೋ — ಆರೋಗ್ಯಕರ",
        "te": "టమాటా — ఆరోగ్యంగా ఉంది",
        "ta": "தக்காளி — ஆரோக்கியமானது",
        "bn": "টমেটো — সুস্থ",
        "gu": "ટામેટા — તંદુરસ્ત",
        "pa": "ਟਮਾਟਰ — ਸਿਹਤਮੰਦ",
        "ur": "ٹماٹر — صحت مند",
        "severity": "none",
        "treatment": "No treatment needed. Maintain good practices.",
    },
    "Potato_Early_Blight": {
        "en": "Potato Early Blight",
        "hi": "आलू अगेती झुलसा",
        "mr": "बटाटा अर्ली ब्लाइट",
        "kn": "ಆಲೂಗಡ್ಡೆ ಅರ್ಲಿ ಬ್ಲೈಟ್",
        "te": "బంగాళదుంప తొలి ముడత",
        "ta": "உருளைக்கிழங்கு ஆரம்ப கருகல்",
        "bn": "আলু আর্লি ব্লাইট",
        "gu": "બટેટા અર્લી બ્લાઈટ",
        "pa": "ਆਲੂ ਅਗੇਤੀ ਝੁਲਸ",
        "ur": "آلو اگیتی جھلسا",
        "severity": "moderate",
        "treatment": "Apply mancozeb at 2.5g/L water every 10 days",
    },
    "Potato_Late_Blight": {
        "en": "Potato Late Blight",
        "hi": "आलू पछेती झुलसा",
        "mr": "बटाटा लेट ब्लाइट",
        "kn": "ಆಲೂಗಡ್ಡೆ ಲೇಟ್ ಬ್ಲೈಟ್",
        "te": "బంగాళదుంప ఆలస్య ముడత",
        "ta": "உருளைக்கிழங்கு தாமத கருகல்",
        "bn": "আলু লেট ব্লাইট",
        "gu": "બટેટા લેટ બ્લાઈટ",
        "pa": "ਆਲੂ ਪਛੇਤੀ ਝੁਲਸ",
        "ur": "آلو دیر جھلسا",
        "severity": "high",
        "treatment": "Metalaxyl-M 4% + Mancozeb 64% spray",
    },
    "Potato_Healthy": {
        "en": "Potato — Healthy",
        "hi": "आलू — स्वस्थ",
        "mr": "बटाटा — निरोगी",
        "kn": "ಆಲೂಗಡ್ಡೆ — ಆರೋಗ್ಯಕರ",
        "te": "బంగాళదుంప — ఆరోగ్యంగా",
        "ta": "உருளைக்கிழங்கு — ஆரோக்கியம்",
        "bn": "আলু — সুস্থ",
        "gu": "બટેટા — તંદુરસ્ત",
        "pa": "ਆਲੂ — ਸਿਹਤਮੰਦ",
        "ur": "آلو — صحت مند",
        "severity": "none",
        "treatment": "No treatment needed.",
    },
    "Corn_Common_Rust": {
        "en": "Corn Common Rust",
        "hi": "मक्का सामान्य रस्ट रोग",
        "mr": "मका सामान्य गंज रोग",
        "kn": "ಮೆಕ್ಕೆಜೋಳ ಸಾಮಾನ್ಯ ತುಕ್ಕು",
        "te": "మొక్కజొన్న సాధారణ తుప్పు",
        "ta": "சோளம் பொதுவான துரு நோய்",
        "bn": "ভুট্টা সাধারণ মরিচা",
        "gu": "મકાઈ સામાન્ય કથ્થઈ",
        "pa": "ਮੱਕੀ ਆਮ ਜੰਗਾਲ",
        "ur": "مکئی عام زنگ",
        "severity": "moderate",
        "treatment": "Apply propiconazole or trifloxystrobin fungicide",
    },
    "Corn_Northern_Leaf_Blight": {
        "en": "Corn Northern Leaf Blight",
        "hi": "मक्का उत्तरी पत्ती झुलसा",
        "mr": "मका उत्तर पान करपा",
        "kn": "ಮೆಕ್ಕೆಜೋಳ ಉತ್ತರ ಎಲೆ ಒಣ",
        "te": "మొక్కజొన్న ఉత్తర ఆకు ముడత",
        "ta": "சோளம் வடக்கு இலை கருகல்",
        "bn": "ভুট্টা উত্তরের পাতার ব্লাইট",
        "gu": "મકાઈ ઉત્તરીય પાન ઝળ",
        "pa": "ਮੱਕੀ ਉੱਤਰੀ ਪੱਤਾ ਝੁਲਸ",
        "ur": "مکئی شمالی پتی جھلسا",
        "severity": "high",
        "treatment": "Azoxystrobin + propiconazole spray at tasseling",
    },
    "Corn_Gray_Leaf_Spot": {
        "en": "Corn Gray Leaf Spot",
        "hi": "मक्का धूसर पत्ती धब्बा",
        "mr": "मका राखाडी पान ठिपके",
        "kn": "ಮೆಕ್ಕೆಜೋಳ ಬೂದು ಎಲೆ ಚುಕ್ಕೆ",
        "te": "మొక్కజొన్న బూడిద ఆకు మచ్చ",
        "ta": "சோளம் சாம்பல் இலை புள்ளி",
        "bn": "ভুট্টা ধূসর পাতার দাগ",
        "gu": "મкаઈ ধূসর পাত দág",
        "pa": "ਮੱਕੀ ਸਲੇਟੀ ਪੱਤੀ ਧੱਬਾ",
        "ur": "مکئی سرمئی پتی دھبہ",
        "severity": "high",
        "treatment": "Strobilurin fungicides, plant resistant hybrids",
    },
    "Corn_Healthy": {
        "en": "Corn — Healthy",
        "hi": "मक्का — स्वस्थ",
        "mr": "मका — निरोगी",
        "kn": "ಮೆಕ್ಕೆຈోಳ — ಆರೋಗ್ಯಕರ",
        "te": "మొక్కజొన్న — ఆరోగ్యం",
        "ta": "சோளம் — ஆரோக்கியம்",
        "bn": "ভুট্টা — সুস্থ",
        "gu": "мकаઈ — તंдуरсть",
        "pa": "ਮੱਕੀ — ਸਿਹਤਮੰਦ",
        "ur": "مکئی — صحت مند",
        "severity": "none",
        "treatment": "No treatment needed.",
    },
    "Wheat_Brown_Rust": {
        "en": "Wheat Brown Rust (Leaf Rust)",
        "hi": "गेहूं भूरा रतुआ रोग",
        "mr": "गहू तपकिरी गंज रोग",
        "kn": "ಗೋಧಿ ಕಂದು ತುಕ್ಕು",
        "te": "గోధుమ గోధుమ రంగు తుప్పు",
        "ta": "கோதுமை பழுப்பு துரு நோய்",
        "bn": "গম বাদামী মরিচা",
        "gu": "ઘઉં ભૂરી ગ્રહ",
        "pa": "ਕਣਕ ਭੂਰਾ ਜੰਗਾਲ",
        "ur": "گندم بھوری زنگ",
        "severity": "high",
        "treatment": "Propiconazole 25EC @ 0.1% spray",
    },
    "Wheat_Yellow_Rust": {
        "en": "Wheat Yellow Rust (Stripe Rust)",
        "hi": "गेहूं पीला रतुआ (धारीदार रोग)",
        "mr": "गहू पिवळा गंज",
        "kn": "ಗೋಧಿ ಹಳದಿ ತುಕ್ಕು",
        "te": "గోధుమ పసుపు తుప్పు",
        "ta": "கோதுமை மஞ்சள் துரு",
        "bn": "গম হলুদ মরিচা",
        "gu": "ઘઉં પીળી ગ્રહ",
        "pa": "ਕਣਕ ਪੀਲਾ ਜੰਗਾਲ",
        "ur": "گندم پیلی زنگ",
        "severity": "high",
        "treatment": "Tebuconazole or propiconazole spray immediately",
    },
    "Wheat_Loose_Smut": {
        "en": "Wheat Loose Smut",
        "hi": "गेहूं अनावृत कंड रोग",
        "mr": "गहू उघडा काजळी रोग",
        "kn": "ಗೋಧಿ ಸಡಿಲ ಕಪ್ಪು ಸ್ಮಟ್",
        "te": "గోధుమ వదులు నల్ల తెగులు",
        "ta": "கோதுமை இலகு ஸ்மட்",
        "bn": "গম লুজ স্মাট",
        "gu": "ઘઉં ઢીલું ઘૂળ",
        "pa": "ਕਣਕ ਢਿੱਲੀ ਕਾਲਖ",
        "ur": "گندم ڈھیلی کند",
        "severity": "moderate",
        "treatment": "Seed treatment with carboxin 37.5%+thiram 37.5%",
    },
    "Wheat_Healthy": {
        "en": "Wheat — Healthy",
        "hi": "गेहूं — स्वस्थ",
        "mr": "गहू — निरोगी",
        "kn": "ಗೋಧಿ — ಆರೋಗ್ಯಕರ",
        "te": "గోధుమ — ఆరోగ్యం",
        "ta": "கோதுமை — ஆரோக்கியம்",
        "bn": "গম — সুস্থ",
        "gu": "ઘઉં — તंदुरस्त",
        "pa": "ਕਣਕ — ਸਿਹਤਮੰਦ",
        "ur": "گندم — صحت مند",
        "severity": "none",
        "treatment": "No treatment needed.",
    },
    "Rice_Leaf_Blast": {
        "en": "Rice Leaf Blast",
        "hi": "धान पत्ती झोंका रोग",
        "mr": "भात पान ब्लास्ट",
        "kn": "ಭತ್ತ ಎಲೆ ಸ್ಫೋಟ ರೋಗ",
        "te": "వరి ఆకు పేలుడు తెగులు",
        "ta": "நெல் இலை வெடிப்பு நோய்",
        "bn": "ধান পাতা ব্লাস্ট",
        "gu": "ડાంગર પાન ઝળ",
        "pa": "ਝੋਨਾ ਪੱਤਾ ਝੋਕਾ",
        "ur": "دھان پتی بلاسٹ",
        "severity": "high",
        "treatment": "Tricyclazole 75 WP @ 0.6 g/L spray",
    },
    "Rice_Brown_Spot": {
        "en": "Rice Brown Spot",
        "hi": "धान भूरा धब्बा रोग",
        "mr": "भात तपकिरी डाग",
        "kn": "ಭತ್ತ ಕಂದು ಚುಕ್ಕೆ ರೋಗ",
        "te": "వరి గోధుమ మచ్చ తెగులు",
        "ta": "நெல் பழுப்பு புள்ளி நோய்",
        "bn": "ধান বাদামী দাগ",
        "gu": "ডাংগর ভূরা ডাগ",
        "pa": "ਝੋਨਾ ਭੂਰਾ ਧੱਬਾ",
        "ur": "دھان بھوری دھبہ",
        "severity": "moderate",
        "treatment": "Mancozeb or edifenphos spray",
    },
    "Rice_Bacterial_Blight": {
        "en": "Rice Bacterial Blight (BLB)",
        "hi": "धान जीवाणु झुलसा (BLB)",
        "mr": "भात जीवाणुजन्य करपा",
        "kn": "ಭತ್ತ ಬ್ಯಾಕ್ಟೀರಿಯಲ್ ಎಲೆ ಒಣ",
        "te": "వరి బాక్టీరియల్ బ్లైట్",
        "ta": "நெல் பாக்டீரியல் கருகல்",
        "bn": "ধান ব্যাকটেরিয়াল ব্লাইট",
        "gu": "डांगर बेक्टेरियल करपो",
        "pa": "ਝੋਨਾ ਬੈਕਟੀਰੀਅਲ ਝੁਲਸ",
        "ur": "دھان بیکٹیریائی جھلسا",
        "severity": "high",
        "treatment": "Streptomycin 500ppm + copper oxychloride spray",
    },
    "Rice_Healthy": {
        "en": "Rice — Healthy",
        "hi": "धान — स्वस्थ",
        "mr": "भात — निरोगी",
        "kn": "ಭತ್ತ — ಆರೋಗ್ಯಕರ",
        "te": "వరి — ఆరోగ్యం",
        "ta": "நெல் — ஆரோக்கியம்",
        "bn": "ধান — সুস্থ",
        "gu": "ডাংগர — तंदुरस्त",
        "pa": "ਝੋਨਾ — ਸਿਹਤਮੰਦ",
        "ur": "دھان — صحت مند",
        "severity": "none",
        "treatment": "No treatment needed.",
    },
    "Apple_Apple_Scab": {
        "en": "Apple Scab",
        "hi": "सेब स्कैब रोग",
        "mr": "सफरचंद खरूज रोग",
        "kn": "ಸೇಬು ಸ್ಕ್ಯಾಬ್",
        "te": "యాపిల్ స్కాబ్",
        "ta": "ஆப்பிள் ஸ்காப்",
        "bn": "আপেল স্ক্যাব",
        "gu": "સફ‍રjanu ખరજ",
        "pa": "ਸੇਬ ਖੁਰ",
        "ur": "سیب کا خارش",
        "severity": "moderate",
        "treatment": "Captan or mancozeb spray at bud break",
    },
    "Apple_Black_Rot": {
        "en": "Apple Black Rot",
        "hi": "सेब काला सड़न",
        "mr": "सफरचंद काळे कूज",
        "kn": "ಸೇಬು ಕಪ್ಪು ಕೊಳೆ",
        "te": "యాపిల్ నల్ల తెగులు",
        "ta": "ஆப்பிள் கருப்பு அழுகல்",
        "bn": "আপেল কালো পচন",
        "gu": "સফ‍rjanu કالو સડો",
        "pa": "ਸੇਬ ਕਾਲੀ ਗਲਣ",
        "ur": "سیب کالا سڑن",
        "severity": "high",
        "treatment": "Prune infected wood, captan or ziram spray",
    },
    "Apple_Cedar_Rust": {
        "en": "Apple Cedar Apple Rust",
        "hi": "सेब देवदार जंग रोग",
        "mr": "सफरचंद सीडर गंज",
        "kn": "ಸೇಬು ಸೀಡರ್ ತುಕ್ಕು",
        "te": "యాపిల్ సీడర్ తుప్పు",
        "ta": "ஆப்பிள் சீடர் துரு",
        "bn": "আপেল সিডার মরিচা",
        "gu": "સफ‍rjanu Rust",
        "pa": "ਸੇਬ ਜੰਗਾਲ",
        "ur": "سیب زنگ",
        "severity": "moderate",
        "treatment": "Myclobutanil spray during wet spring weather",
    },
    "Apple_Healthy": {
        "en": "Apple — Healthy",
        "hi": "सेब — स्वस्थ",
        "mr": "सफरचंद — निरोगी",
        "kn": "ಸೇಬು — ಆರೋಗ್ಯಕರ",
        "te": "యాపిల్ — ఆరోగ్యం",
        "ta": "ஆப்பிள் — ஆரோக்கியம்",
        "bn": "আপেল — সুস্থ",
        "gu": "Sapharajanu — Tandurst",
        "pa": "ਸੇਬ — ਸਿਹਤਮੰਦ",
        "ur": "سیب — صحت مند",
        "severity": "none",
        "treatment": "No treatment needed.",
    },
    "Grape_Black_Rot": {
        "en": "Grape Black Rot",
        "hi": "अंगूर काला सड़न रोग",
        "mr": "द्राक्ष काळे कूज",
        "kn": "ದ್ರಾಕ್ಷಿ ಕಪ್ಪು ಕೊಳೆ",
        "te": "ద్రాక్ష నల్ల తెగులు",
        "ta": "திராட்சை கருப்பு அழுகல்",
        "bn": "আঙুর কালো পচন",
        "gu": "દ્રાક્ષ калो сड़о",
        "pa": "ਅੰਗੂਰ ਕਾਲੀ ਗਲਣ",
        "ur": "انگور کالا سڑن",
        "severity": "high",
        "treatment": "Mancozeb or captan spray starting at bud break",
    },
    "Grape_Leaf_Blight": {
        "en": "Grape Leaf Blight",
        "hi": "अंगूर पत्ती झुलसा",
        "mr": "द्राक्ष पान करपा",
        "kn": "ದ್ರಾಕ್ಷಿ ಎಲೆ ಒಣ",
        "te": "ద్రాక్ష ఆకు ముడత",
        "ta": "திராட்சை இலை கருகல்",
        "bn": "আঙুর পাতার ব্লাইট",
        "gu": "Draaksh Paan Kharpo",
        "pa": "ਅੰਗੂਰ ਪੱਤਾ ਝੁਲਸ",
        "ur": "انگور پتی جھلسا",
        "severity": "moderate",
        "treatment": "Copper-based fungicide spray",
    },
    "Grape_Healthy": {
        "en": "Grape — Healthy",
        "hi": "अंगूर — स्वस्थ",
        "mr": "द्राक्ष — निरोगी",
        "kn": "ದ್ರಾಕ್ಷಿ — ಆರೋಗ್ಯಕರ",
        "te": "ద్రాక్ష — ఆరోగ్యం",
        "ta": "திராட்சை — ஆரோக்கியம்",
        "bn": "আঙুর — সুস্থ",
        "gu": "Draaksh — Tandurst",
        "pa": "ਅੰਗੂਰ — ਸਿਹਤਮੰਦ",
        "ur": "انگور — صحت مند",
        "severity": "none",
        "treatment": "No treatment needed.",
    },
    "Orange_Citrus_Greening": {
        "en": "Citrus Greening (Huanglongbing)",
        "hi": "नींबू हरितीकरण रोग (HLB)",
        "mr": "संत्रा हिरवेपणा रोग",
        "kn": "ಕಿತ್ತಳೆ ಹಸಿರು ರೋಗ",
        "te": "నిమ్మ హ్యువాంగ్లాంగ్బింగ్",
        "ta": "சிட்ரஸ் பச்சையாதல் நோய்",
        "bn": "কমলা সবুজায়ন রোগ",
        "gu": "Limbu Hariyali Rog",
        "pa": "ਸੰਤਰਾ ਹਰਿਆਲੀ ਰੋਗ",
        "ur": "مالٹا سبزی مرض",
        "severity": "high",
        "treatment": "Control psyllid vector, remove infected trees",
    },
    "Pepper_Bacterial_Spot": {
        "en": "Pepper Bacterial Spot",
        "hi": "मिर्च जीवाणु धब्बा",
        "mr": "मिरची बॅक्टेरियल स्पॉट",
        "kn": "ಮೆಣಸಿನ ಬ್ಯಾಕ್ಟೀರಿಯಲ್ ಚುಕ್ಕೆ",
        "te": "మిర్చి బాక్టీరియల్ స్పాట్",
        "ta": "மிளகாய் பாக்டீரியல் புள்ளி",
        "bn": "মরিচ ব্যাকটেরিয়াল স্পট",
        "gu": "Marcha Bacterial Spot",
        "pa": "ਮਿਰਚ ਬੈਕਟੀਰੀਅਲ ਧੱਬਾ",
        "ur": "مرچ بیکٹیریائی دھبہ",
        "severity": "moderate",
        "treatment": "Copper hydroxide spray, disease-free transplants",
    },
    "Pepper_Healthy": {
        "en": "Pepper — Healthy",
        "hi": "मिर्च — स्वस्थ",
        "mr": "मिरची — निरोगी",
        "kn": "ಮೆಣಸು — ಆರೋಗ್ಯಕರ",
        "te": "మిర్చి — ఆరోగ్యం",
        "ta": "மிளகாய் — ஆரோக்கியம்",
        "bn": "মরিচ — সুস্থ",
        "gu": "Marcha — Tandurst",
        "pa": "ਮਿਰਚ — ਸਿਹਤਮੰਦ",
        "ur": "مرچ — صحت مند",
        "severity": "none",
        "treatment": "No treatment needed.",
    },
    "Cotton_Bacterial_Blight": {
        "en": "Cotton Bacterial Blight",
        "hi": "कपास जीवाणु झुलसा",
        "mr": "कापूस जिवाणु करपा",
        "kn": "ಹತ್ತಿ ಬ್ಯಾಕ್ಟೀರಿಯಲ್ ಒಣ",
        "te": "పత్తి బాక్టీరియల్ బ్లైట్",
        "ta": "பருத்தி பாக்டீரியல் கருகல்",
        "bn": "তুলা ব্যাকটেরিয়াল ব্লাইট",
        "gu": "Kapas Bacterial Blight",
        "pa": "ਕਪਾਹ ਬੈਕਟੀਰੀਅਲ ਝੁਲਸ",
        "ur": "کپاس بیکٹیریائی جھلسا",
        "severity": "high",
        "treatment": "Streptomycin 500ppm spray, seed treatment",
    },
    "Cotton_Healthy": {
        "en": "Cotton — Healthy",
        "hi": "कपास — स्वस्थ",
        "mr": "कापूस — निरोगी",
        "kn": "ಹತ್ತಿ — ಆರೋಗ್ಯಕರ",
        "te": "పత్తి — ఆరోగ్యం",
        "ta": "பருத்தி — ஆரோக்கியம்",
        "bn": "তুলা — সুস্থ",
        "gu": "Kapas — Tandurst",
        "pa": "ਕਪਾਹ — ਸਿਹਤਮੰਦ",
        "ur": "کپاس — صحت مند",
        "severity": "none",
        "treatment": "No treatment needed.",
    },
    "Banana_Sigatoka": {
        "en": "Banana Black Sigatoka",
        "hi": "केला काला सिगाटोका रोग",
        "mr": "केळी काळा सिगाटोका",
        "kn": "ಬಾಳೆ ಕಪ್ಪು ಸಿಗಾಟೋಕಾ",
        "te": "అరటి నల్ల సిగటోకా",
        "ta": "வாழை கருப்பு சிகட்டோகா",
        "bn": "কলা কালো সিগাটোকা",
        "gu": "Kela Kalo Sigatoka",
        "pa": "ਕੇਲਾ ਕਾਲਾ ਸੀਗਾਟੋਕਾ",
        "ur": "کیلا کالا سگاٹوکا",
        "severity": "high",
        "treatment": "Propiconazole or tridemorph spray",
    },
    "Banana_Healthy": {
        "en": "Banana — Healthy",
        "hi": "केला — स्वस्थ",
        "mr": "केळी — निरोगी",
        "kn": "ಬಾಳೆ — ಆರೋಗ್ಯಕರ",
        "te": "అరటి — ఆరోగ్యం",
        "ta": "வாழை — ஆரோக்கியம்",
        "bn": "কলা — সুস্থ",
        "gu": "Kela — Tandurst",
        "pa": "ਕੇਲਾ — ਸਿਹਤਮੰਦ",
        "ur": "کیلا — صحت مند",
        "severity": "none",
        "treatment": "No treatment needed.",
    },
    "Onion_Purple_Blotch": {
        "en": "Onion Purple Blotch",
        "hi": "प्याज बैंगनी धब्बा रोग",
        "mr": "कांदा जांभळा डाग",
        "kn": "ಈರುಳ್ಳಿ ನೇರಳೆ ಚುಕ್ಕೆ",
        "te": "ఉల్లిపాయ ఊదా మచ్చ",
        "ta": "வெங்காயம் ஊதா புள்ளி",
        "bn": "পেঁয়াজ বেগুনি দাগ",
        "gu": "Dungri Jambali Dag",
        "pa": "ਪਿਆਜ਼ ਬੈਂਗਣੀ ਧੱਬਾ",
        "ur": "پیاز بنفشی دھبہ",
        "severity": "moderate",
        "treatment": "Mancozeb 75 WP @ 2g/L spray",
    },
    "Onion_Healthy": {
        "en": "Onion — Healthy",
        "hi": "प्याज — स्वस्थ",
        "mr": "कांदा — निरोगी",
        "kn": "ಈರುಳ್ಳಿ — ಆರೋಗ್ಯಕರ",
        "te": "ఉల్లి — ఆరోగ్యం",
        "ta": "வெங்காயம் — ஆரோக்கியம்",
        "bn": "পেঁয়াজ — সুস্থ",
        "gu": "Dungri — Tandurst",
        "pa": "ਪਿਆਜ਼ — ਸਿਹਤਮੰਦ",
        "ur": "پیاز — صحت مند",
        "severity": "none",
        "treatment": "No treatment needed.",
    },
    "Groundnut_Leaf_Spot": {
        "en": "Groundnut/Peanut Leaf Spot",
        "hi": "मूंगफली पत्ती धब्बा रोग",
        "mr": "भुईमूग पान ठिपके",
        "kn": "ಕಡಲೇ ಎಲೆ ಚುಕ್ಕೆ",
        "te": "వేరుశనగ ఆకు మచ్చ",
        "ta": "நிலக்கடலை இலை புள்ளி",
        "bn": "চীনাবাদাম পাতার দাগ",
        "gu": "Singdana Pan Tikak",
        "pa": "ਮੂੰਗਫਲੀ ਪੱਤਾ ਧੱਬਾ",
        "ur": "مونگ پھلی پتی دھبہ",
        "severity": "moderate",
        "treatment": "Chlorothalonil or mancozeb spray every 14 days",
    },
    "Groundnut_Healthy": {
        "en": "Groundnut — Healthy",
        "hi": "मूंगफली — स्वस्थ",
        "mr": "भुईमूग — निरोगी",
        "kn": "ಕಡಲೇ — ಆರೋಗ್ಯಕರ",
        "te": "వేరుశనగ — ఆరోగ్యం",
        "ta": "நிலக்கடலை — ஆரோக்கியம்",
        "bn": "চীনাবাদাম — সুস্থ",
        "gu": "Singdana — Tandurst",
        "pa": "ਮੂੰਗਫਲੀ — ਸਿਹਤਮੰਦ",
        "ur": "مونگ پھلی — صحت مند",
        "severity": "none",
        "treatment": "No treatment needed.",
    },
    "Soybean_Rust": {
        "en": "Soybean Rust",
        "hi": "सोयाबीन रस्ट रोग",
        "mr": "सोयाबीन गंज रोग",
        "kn": "ಸೋಯಾಬೀನ್ ತುಕ್ಕು",
        "te": "సోయాబీన్ తుప్పు",
        "ta": "சோயாபீன் துரு நோய்",
        "bn": "সয়াবিন মরিচা",
        "gu": "Soyabin Rust",
        "pa": "ਸੋਇਆਬੀਨ ਜੰਗਾਲ",
        "ur": "سویابین زنگ",
        "severity": "high",
        "treatment": "Trifloxystrobin+tebuconazole fungicide spray",
    },
    "Soybean_Healthy": {
        "en": "Soybean — Healthy",
        "hi": "सोयाबीन — स्वस्थ",
        "mr": "सोयाबीन — निरोगी",
        "kn": "ಸೋಯಾಬೀನ್ — ಆರೋಗ್ಯಕರ",
        "te": "సోయాబీన్ — ఆరోగ్యం",
        "ta": "சோயாபீன் — ஆரோக்கியம்",
        "bn": "সয়াবিন — সুস্থ",
        "gu": "Soyabin — Tandurst",
        "pa": "ਸੋਇਆਬੀਨ — ਸਿਹਤਮੰਦ",
        "ur": "سویابین — صحت مند",
        "severity": "none",
        "treatment": "No treatment needed.",
    },
    "Sugarcane_Red_Rot": {
        "en": "Sugarcane Red Rot",
        "hi": "गन्ना लाल सड़न रोग",
        "mr": "ऊस लाल कूज रोग",
        "kn": "ಕಬ್ಬು ಕೆಂಪು ಕೊಳೆ",
        "te": "చెరకు ఎరుపు తెగులు",
        "ta": "கரும்பு சிவப்பு அழுகல்",
        "bn": "আখ লাল পচন",
        "gu": "Ganna Lalo Sadano",
        "pa": "ਗੰਨਾ ਲਾਲ ਗਲਣ",
        "ur": "گنا لال سڑن",
        "severity": "high",
        "treatment": "Hot water treatment, disease-free setts",
    },
    "Cherry_Powdery_Mildew": {
        "en": "Cherry Powdery Mildew",
        "hi": "चेरी चूर्णिल फफूंद",
        "mr": "चेरी भुकटी बुरशी",
        "kn": "ಚೆರ್ರಿ ಪೌಡರ್ ಶಿಲೀಂಧ್ರ",
        "te": "చెర్రీ పొడి బూజు",
        "ta": "செர்ரி பொடி பூஞ்சை",
        "bn": "চেরি গুঁড়া ছত্রাক",
        "gu": "Cherry Bhukti Fungi",
        "pa": "ਚੈਰੀ ਚੂਰਨੀ ਉੱਲੀ",
        "ur": "چیری پاؤڈری پھپھوندی",
        "severity": "moderate",
        "treatment": "Sulphur-based fungicide or potassium bicarbonate",
    },
    "Squash_Powdery_Mildew": {
        "en": "Squash Powdery Mildew",
        "hi": "कद्दू चूर्णिल फफूंद",
        "mr": "भोपळा भुकटी बुरशी",
        "kn": "ಕಲ್ಲಂಗಡಿ ಪೌಡರ್ ಶಿಲೀಂಧ್ರ",
        "te": "గుమ్మడి పొడి బూజు",
        "ta": "பூசணி பொடி பூஞ்சை",
        "bn": "কুমড়া গুঁড়া ছত্রাক",
        "gu": "Kaddu Powdery Mildew",
        "pa": "ਕੱਦੂ ਚੂਰਨੀ ਉੱਲੀ",
        "ur": "کدو پاؤڈری پھپھوندی",
        "severity": "moderate",
        "treatment": "Neem oil or potassium bicarbonate spray",
    },
    "Strawberry_Leaf_Scorch": {
        "en": "Strawberry Leaf Scorch",
        "hi": "स्ट्रॉबेरी पत्ती झुलसन",
        "mr": "स्ट्रॉबेरी पान जळणे",
        "kn": "ಸ್ಟ್ರಾಬೆರಿ ಎಲೆ ಸುಟ್ಟ",
        "te": "స్ట్రాబెర్రీ ఆకు కాలిపోవడం",
        "ta": "ஸ்ட்ராபெரி இலை கருகல்",
        "bn": "স্ট্রবেরী পাতা পোড়া",
        "gu": "Strawberry Pan Jalaavu",
        "pa": "ਸਟ੍ਰਾਬੇਰੀ ਪੱਤਾ ਝੁਲਸਣ",
        "ur": "اسٹرابیری پتی جھلسن",
        "severity": "moderate",
        "treatment": "Captan or myclobutanil spray",
    },
    "Peach_Bacterial_Spot": {
        "en": "Peach Bacterial Spot",
        "hi": "आड़ू जीवाणु धब्बा",
        "mr": "पीच बॅक्टेरियल स्पॉट",
        "kn": "ಪೀಚ್ ಬ್ಯಾಕ್ಟೀರಿಯಲ್ ಚುಕ್ಕೆ",
        "te": "పీచ్ బాక్టీరియల్ స్పాట్",
        "ta": "பீச் பாக்டீரியல் புள்ளி",
        "bn": "পিচ ব্যাকটেরিয়াল স্পট",
        "gu": "Peach Bacterial Spot",
        "pa": "ਆੜੂ ਬੈਕਟੀਰੀਅਲ ਧੱਬਾ",
        "ur": "آڑو بیکٹیریائی دھبہ",
        "severity": "moderate",
        "treatment": "Copper-based bactericide",
    },
    "Grape_Esca_Black_Measles": {
        "en": "Grape Esca (Black Measles)",
        "hi": "अंगूर एस्का रोग",
        "mr": "द्राक्ष एस्का रोग",
        "kn": "ದ್ರಾಕ್ಷಿ ಎಸ್ಕಾ",
        "te": "ద్రాక్ష ఎస్కా",
        "ta": "திராட்சை எஸ்கா நோய்",
        "bn": "আঙুর এস্কা রোগ",
        "gu": "Draaksh Esca Rog",
        "pa": "ਅੰਗੂਰ ਏਸਕਾ ਰੋਗ",
        "ur": "انگور ایسکا مرض",
        "severity": "high",
        "treatment": "Remove infected wood, trunk injections",
    },
}

# Fallback for classes not in above dict — generate from class name
def get_disease_info(class_name: str, lang: str = "en") -> dict:
    if class_name in DISEASE_TRANSLATIONS:
        info = DISEASE_TRANSLATIONS[class_name]
        return {
            "name": info.get(lang, info.get("en", class_name)),
            "name_en": info.get("en", class_name),
            "severity": info.get("severity", "moderate"),
            "treatment": info.get("treatment", "Consult local agricultural officer"),
        }
    # Auto-generate for unknown classes
    parts = class_name.replace("_", " ").split()
    return {
        "name": class_name.replace("_", " "),
        "name_en": class_name.replace("_", " "),
        "severity": "unknown",
        "treatment": "Consult local agricultural officer (KVK)",
    }


SUPPORTED_LANGUAGES = {
    "en": "English",
    "hi": "Hindi",
    "mr": "Marathi",
    "kn": "Kannada",
    "te": "Telugu",
    "ta": "Tamil",
    "bn": "Bengali",
    "gu": "Gujarati",
    "pa": "Punjabi",
    "ur": "Urdu",
}

# BCP-47 language codes for TTS / speech synthesis
TTS_LANG_CODES = {
    "en": "en-IN",
    "hi": "hi-IN",
    "mr": "mr-IN",
    "kn": "kn-IN",
    "te": "te-IN",
    "ta": "ta-IN",
    "bn": "bn-IN",
    "gu": "gu-IN",
    "pa": "pa-IN",
    "ur": "ur-IN",
}
