import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'hi' | 'mr' | 'kn';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.cropScan': 'Crop Scan',
    'nav.yieldPrediction': 'Yield Prediction',
    'nav.marketPrices': 'Market Prices',
    'nav.nearbyMarkets': 'Nearby Markets',
    'nav.policies': 'Government Policies',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    
    // Landing Page
    'landing.hero.title': 'Smart Farming for a Better Tomorrow',
    'landing.hero.subtitle': 'AI-powered agricultural solutions to maximize your yield, detect crop diseases early, and get real-time market insights.',
    'landing.hero.getStarted': 'Get Started Free',
    'landing.hero.learnMore': 'Learn More',
    'landing.features.title': 'Powerful Features for Modern Farmers',
    'landing.features.subtitle': 'Everything you need to optimize your farming operations',
    'landing.cropScan.title': 'AI Crop Disease Detection',
    'landing.cropScan.desc': 'Upload photos of your crops and get instant AI-powered disease diagnosis with treatment recommendations.',
    'landing.yield.title': 'Yield Prediction',
    'landing.yield.desc': 'Get accurate yield predictions based on your crop type, soil conditions, and farming practices.',
    'landing.market.title': 'Live Market Prices',
    'landing.market.desc': 'Track real-time prices of agricultural commodities across different markets in India.',
    'landing.nearby.title': 'Find Nearby Markets',
    'landing.nearby.desc': 'Locate agricultural markets near you with contact details and available crops.',
    'landing.policy.title': 'Government Schemes',
    'landing.policy.desc': 'Stay updated with the latest government policies and subsidies for farmers.',
    'landing.chat.title': 'AI Farming Assistant',
    'landing.chat.desc': 'Get instant answers to your farming questions from our AI-powered chatbot.',
    'landing.cta.title': 'Ready to Transform Your Farming?',
    'landing.cta.subtitle': 'Join thousands of farmers who are already using FarmGenius to improve their yields.',
    'landing.cta.button': 'Start Your Journey',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.subtitle': 'Here\'s what\'s happening with your farm today',
    'dashboard.weather': 'Weather Today',
    'dashboard.tips': 'Agricultural Tips',
    'dashboard.quickStats': 'Quick Stats',
    'dashboard.cropScans': 'Crop Scans',
    'dashboard.predictions': 'Predictions',
    'dashboard.markets': 'Markets',
    'dashboard.nearbyMarkets': 'Nearby Markets',
    'dashboard.farmer': 'Farmer',
    'dashboard.sunny': 'Sunny',
    'dashboard.viewNotifications': 'View Notifications',
    'dashboard.updateProfile': 'Update Profile',
    'dashboard.scanNow': 'Scan Now',
    'dashboard.predictNow': 'Predict Now',
    'dashboard.viewPrices': 'View Prices',
    'dashboard.findMarkets': 'Find Markets',
    'dashboard.weatherForecast': '7-Day Weather Forecast',
    'dashboard.today': 'Today',
    'dashboard.tue': 'Tue',
    'dashboard.wed': 'Wed',
    'dashboard.thu': 'Thu',
    'dashboard.fri': 'Fri',
    'dashboard.sat': 'Sat',
    'dashboard.sun': 'Sun',
    'dashboard.wind': 'Wind',
    'dashboard.humidity': 'Humidity',
    'dashboard.uvIndex': 'UV Index',
    'dashboard.tipsAlerts': 'Tips & Alerts',
    'dashboard.readMore': 'Read More',
    'dashboard.avgWheatPrice': 'Avg Wheat Price',
    
    // Crop Scan
    'cropScan.title': 'AI Crop Disease Detection',
    'cropScan.subtitle': 'Upload a photo of your crop to detect diseases and get treatment recommendations',
    'cropScan.upload': 'Upload Crop Image',
    'cropScan.uploadDesc': 'Take a clear photo of the affected plant part for accurate disease detection',
    'cropScan.dragDrop': 'or drag and drop image here',
    'cropScan.chooseFile': 'Choose File',
    'cropScan.fileTypes': 'PNG, JPG up to 5MB',
    'cropScan.changeImage': 'Change Image',
    'cropScan.analyzing': 'Analyzing...',
    'cropScan.analyze': 'Analyze Disease',
    'cropScan.results': 'Analysis Results',
    'cropScan.disease': 'Disease Detected',
    'cropScan.detected': 'Detected',
    'cropScan.severity': 'severity',
    'cropScan.confidence': 'Confidence',
    'cropScan.description': 'Description',
    'cropScan.affectedParts': 'Affected Parts',
    'cropScan.recommendations': 'Recommended Actions',
    'cropScan.history': 'Previous Scans',
    'cropScan.fileTooLarge': 'File too large',
    'cropScan.fileTooLargeDesc': 'Please select an image under 5MB',
    'cropScan.analysisComplete': 'Analysis Complete',
    'cropScan.analysisCompleteDesc': 'Your crop has been analyzed successfully.',
    'cropScan.analysisFailed': 'Analysis Failed',
    'cropScan.tryAgain': 'Please try again later.',
    'cropScan.tipsTitle': 'How to get the best results',
    'cropScan.tip1': 'Take close-up photos of affected areas',
    'cropScan.tip2': 'Ensure good lighting conditions',
    'cropScan.tip3': 'Include both healthy and diseased parts for comparison',
    'cropScan.tip4': 'Avoid shadows and reflections',
    'cropScan.commonDiseases': 'Common Crop Diseases',
    'cropScan.disease1': 'Leaf Blight',
    'cropScan.disease2': 'Powdery Mildew',
    'cropScan.disease3': 'Root Rot',
    'cropScan.disease4': 'Bacterial Wilt',
    'cropScan.clickToLearn': 'Click to learn more',
    
    // Yield Prediction
    'yield.title': 'Crop Yield Prediction',
    'yield.subtitle': 'Get AI-powered yield forecasts based on your crop and field conditions',
    'yield.cropType': 'Crop Type',
    'yield.soilType': 'Soil Type',
    'yield.area': 'Area (Acres)',
    'yield.sowingDate': 'Sowing Date',
    'yield.irrigation': 'Irrigation Type',
    'yield.fertilizer': 'Fertilizer Used',
    'yield.predict': 'Predict Yield',
    'yield.predicting': 'Predicting...',
    'yield.results': 'Prediction Results',
    'yield.estimatedYield': 'Estimated Yield',
    'yield.revenue': 'Est. Revenue',
    'yield.harvestDays': 'Days to Harvest',
    'yield.enterDetails': 'Enter Crop Details',
    'yield.selectCrop': 'Select crop',
    'yield.selectSoil': 'Select soil type',
    'yield.enterArea': 'Enter area',
    'yield.selectIrrigation': 'Select irrigation',
    'yield.selectFertilizer': 'Select fertilizer',
    'yield.fillRequired': 'Please fill all required fields',
    'yield.predictionComplete': 'Prediction Complete',
    'yield.predictionReady': 'Your yield prediction is ready.',
    'yield.predictionFailed': 'Prediction Failed',
    'yield.recommendations': 'Recommendations',
    'yield.riskFactors': 'Risk Factors',
    'yield.generateReport': 'Generate Detailed Report',
    'yield.noPrediction': 'No Prediction Yet',
    'yield.noPredictionDesc': 'Enter your crop details on the left to get an AI-powered yield prediction with recommendations.',
    'yield.vsAverage': 'vs Average',
    
    // Crops
    'crops.wheat': 'Wheat',
    'crops.rice': 'Rice',
    'crops.maize': 'Maize',
    'crops.potato': 'Potato',
    'crops.cotton': 'Cotton',
    
    // Soil
    'soil.loamy': 'Loamy',
    'soil.sandy': 'Sandy',
    'soil.clay': 'Clay',
    'soil.silty': 'Silty',
    'soil.black': 'Black',
    
    // Irrigation
    'irrigation.drip': 'Drip Irrigation',
    'irrigation.sprinkler': 'Sprinkler',
    'irrigation.flood': 'Flood Irrigation',
    'irrigation.rainfed': 'Rainfed',
    
    // Fertilizer
    'fertilizer.urea': 'Urea',
    'fertilizer.organic': 'Organic',
    'fertilizer.mixed': 'Mixed',
    
    // Market Prices
    'market.title': 'Market Information',
    'market.subtitle': 'Current market prices for agricultural commodities across India',
    'market.search': 'Search by crop, variety or market...',
    'market.filter': 'Filter by market',
    'market.allMarkets': 'All Markets',
    'market.allCrops': 'All Crops',
    'market.allLocations': 'All Locations',
    'market.filterPrices': 'Filter Prices',
    'market.crop': 'Crop',
    'market.variety': 'Variety',
    'market.marketName': 'Market',
    'market.price': 'Price (₹/Quintal)',
    'market.trend': 'Trend',
    'market.location': 'Location',
    'market.currentPrices': 'Current Market Prices',
    'market.lastUpdated': 'Last Updated',
    'market.justNow': 'Just now',
    'market.hoursAgo': 'hours ago',
    'market.daysAgo': 'days ago',
    'market.dataSource': 'Data source: Agricultural Produce Market Committee (APMC)',
    'market.priceTrends': 'Price Trends (Last 30 Days)',
    'market.trendChart': 'Price trend chart',
    'market.marketComparison': 'Market Comparison',
    'market.comparisonChart': 'Market comparison chart',
    
    // Nearby Markets
    'nearby.title': 'Nearby Markets',
    'nearby.subtitle': 'Find agricultural markets near your location',
    'nearby.search': 'Search markets...',
    'nearby.call': 'Call',
    'nearby.directions': 'Get Directions',
    'nearby.getDirections': 'Get Directions',
    'nearby.crops': 'Available Crops',
    'nearby.availableCrops': 'Available Crops',
    'nearby.hours': 'Opening Hours',
    'nearby.rating': 'Rating',
    'nearby.findMarkets': 'Find Markets Near You',
    'nearby.useLocation': 'Use Current Location',
    'nearby.distance': 'Distance',
    'nearby.interactiveMap': 'Interactive Map',
    'nearby.marketsOnMap': 'Markets shown on map',
    'nearby.loadingMarkets': 'Loading markets...',
    'nearby.noMarkets': 'No markets found',
    'nearby.adjustFilters': 'Try adjusting your filters',
    
    // Policies
    'policies.title': 'Government Policies',
    'policies.subtitle': 'Agricultural policies, schemes, and programs for farmers',
    'policies.search': 'Search policies...',
    'policies.all': 'All',
    'policies.allPolicies': 'All Policies',
    'policies.subsidy': 'Subsidy',
    'policies.subsidies': 'Subsidies',
    'policies.insurance': 'Insurance',
    'policies.loan': 'Loan',
    'policies.loanSchemes': 'Loan Schemes',
    'policies.program': 'Program',
    'policies.programs': 'Programs',
    'policies.support': 'Support',
    'policies.readMore': 'Read More',
    'policies.loading': 'Loading policies...',
    'policies.noPolicies': 'No policies found',
    'policies.checkBack': 'Check back later for updates',
    
    // Auth
    'auth.login': 'Login',
    'auth.signup': 'Sign Up',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'Enter your email',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': 'Enter your password',
    'auth.fullName': 'Full Name',
    'auth.fullNamePlaceholder': 'Enter your full name',
    'auth.phone': 'Phone Number',
    'auth.phonePlaceholder': 'Enter your phone number',
    'auth.village': 'Village/City',
    'auth.villageCity': 'Village/City',
    'auth.villageCityPlaceholder': 'Enter your village or city',
    'auth.role': 'I am a',
    'auth.iAmA': 'I am a',
    'auth.selectRole': 'Select role',
    'auth.farmer': 'Farmer',
    'auth.dealer': 'Dealer',
    'auth.confirmPassword': 'Confirm Password',
    'auth.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.loginButton': 'Login',
    'auth.signupButton': 'Create Account',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.alreadyRegisteredQ': 'Already registered?',
    'auth.hasAccount': 'Already have an account?',
    'auth.loginTitle': 'Login to FarmGenius',
    'auth.createAccount': 'Create an Account',
    'auth.loginSubtitle': 'Enter your credentials to access your account',
    'auth.registerSubtitle': 'Enter your details to register for FarmGenius',
    'auth.invalidEmail': 'Please enter a valid email',
    'auth.passwordMin': 'Password must be at least 6 characters',
    'auth.nameMin': 'Name must be at least 2 characters',
    'auth.passwordMismatch': 'Passwords don\'t match',
    'auth.loginFailed': 'Login Failed',
    'auth.invalidCredentials': 'Invalid email or password. Please try again.',
    'auth.welcomeBack': 'Welcome back!',
    'auth.loginSuccess': 'You have successfully logged in.',
    'auth.accountExists': 'Account Exists',
    'auth.alreadyRegistered': 'This email is already registered. Please login instead.',
    'auth.registrationFailed': 'Registration Failed',
    'auth.welcomeToFarmGenius': 'Welcome to FarmGenius!',
    'auth.accountCreated': 'Your account has been created successfully.',
    
    // Chat
    'chat.title': 'FarmGenius AI',
    'chat.placeholder': 'Ask about farming...',
    'chat.send': 'Send',
    'chat.greeting': 'Namaste! I\'m your AI farming assistant. How can I help you today?',
    
    // Footer
    'footer.quickLinks': 'Quick Links',
    'footer.helpSupport': 'Help & Support',
    'footer.contactUs': 'Contact Us',
    'footer.faq': 'FAQ',
    'footer.tutorials': 'Tutorials',
    'footer.feedback': 'Feedback',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.rights': 'All rights reserved.',
    'footer.tagline': 'Empowering farmers with AI-driven insights for better crop management, disease detection, and market intelligence.',
    
    // Stats
    'stats.farmersHelped': 'Farmers Helped',
    'stats.accuracy': 'Detection Accuracy',
    'stats.marketsListed': 'Markets Listed',
    'stats.aiSupport': 'AI Support',
    
    // Benefits
    'benefits.title': 'Why Farmers Choose FarmGenius',
    'benefits.subtitle': 'Join thousands of farmers who are already using AI to improve their crop yields and make smarter decisions.',
    'benefits.free': 'Free to use for all farmers',
    'benefits.languages': 'Works in multiple Indian languages',
    'benefits.noExpertise': 'No technical expertise required',
    'benefits.experts': 'Backed by agricultural experts',
    'benefits.updates': 'Regular updates with new features',
    'benefits.community': 'Community support & forums',
    'benefits.startButton': 'Start Using FarmGenius',
    'benefits.smartAg': 'Smart Agriculture',
    'benefits.poweredByAI': 'Powered by AI',
    
    // Hero badge
    'landing.hero.badge': 'AI-Powered Agricultural Solutions',
    
    // Common
    'common.loading': 'Loading...',
    'common.error': 'An error occurred',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.search': 'Search',
    'common.refresh': 'Refresh',
    'common.share': 'Share',
    'common.print': 'Print',
    'common.tryAgain': 'Please try again later.',
    'common.pleaseLogin': 'Please login',
    
    // Profile
    'profile.title': 'My Profile',
    'profile.subtitle': 'Update your personal information',
    'profile.email': 'Email',
    'profile.emailHint': 'Email cannot be changed',
    'profile.fullName': 'Full Name',
    'profile.fullNamePlaceholder': 'Enter your full name',
    'profile.phone': 'Phone Number',
    'profile.phonePlaceholder': 'Enter your phone number',
    'profile.village': 'Village/City',
    'profile.villagePlaceholder': 'Enter your village or city',
    'profile.save': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.success': 'Profile updated successfully!',
    'profile.error': 'Failed to update profile. Please try again.',
    'profile.changePhoto': 'Change Photo',
    'profile.uploadingPhoto': 'Uploading...',
    'profile.photoSuccess': 'Photo updated successfully!',
    'profile.photoError': 'Failed to upload photo. Please try again.',
    
    // Dealer
    'dealer.dashboard': 'Dealer Dashboard',
    'dealer.welcome': 'Welcome',
    'dealer.subtitle': 'Manage your trading operations from your dealer dashboard',
    'dealer.buyOffers': 'Buy Offers',
    'dealer.buyOffersDesc': 'Post offers to buy crops from farmers at your desired price',
    'dealer.farmerDirectory': 'Farmer Directory',
    'dealer.farmerDirectoryDesc': 'Browse and contact farmers in your area',
    'dealer.inventory': 'Inventory',
    'dealer.inventoryDesc': 'Track crops purchased and manage your stock',
    'dealer.orders': 'Orders',
    'dealer.ordersDesc': 'Manage orders, deliveries, and payments',
    'dealer.activeOffers': 'Active Offers',
    'dealer.quintalsInStock': 'Quintals in Stock',
    'dealer.pendingOrders': 'Pending Orders',
    'dealer.completed': 'Completed',
    'dealer.quickActions': 'Quick Actions',
    'dealer.postNewOffer': 'Post New Buy Offer',
    'dealer.addInventory': 'Add Inventory',
    'dealer.checkPrices': 'Check Market Prices',
    'dealer.newOffer': 'New Offer',
    'dealer.createOffer': 'Create Buy Offer',
    'dealer.editOffer': 'Edit Offer',
    'dealer.crop': 'Crop',
    'dealer.variety': 'Variety',
    'dealer.quantity': 'Quantity (Quintals)',
    'dealer.pricePerQuintal': 'Price (₹/Quintal)',
    'dealer.location': 'Location',
    'dealer.description': 'Description',
    'dealer.status': 'Status',
    'dealer.active': 'Active',
    'dealer.closed': 'Closed',
    'dealer.expired': 'Expired',
    'dealer.closeOffer': 'Close Offer',
    'dealer.reactivate': 'Reactivate',
    'dealer.noOffers': 'No buy offers found',
    'dealer.createFirst': 'Create Your First Offer',
    'dealer.browseFarmers': 'Browse Farmers',
    'dealer.searchFarmers': 'Search farmers by name or location...',
    'dealer.noFarmers': 'No farmers found',
    'dealer.contact': 'Contact',
    'dealer.call': 'Call',
    'dealer.addToInventory': 'Add to Inventory',
    'dealer.farmerName': 'Farmer Name',
    'dealer.purchaseDate': 'Purchase Date',
    'dealer.purchasePrice': 'Purchase Price',
    'dealer.notes': 'Notes',
    'dealer.noInventory': 'No inventory items',
    'dealer.createOrder': 'Create Order',
    'dealer.orderDetails': 'Order Details',
    'dealer.totalAmount': 'Total Amount',
    'dealer.paymentStatus': 'Payment Status',
    'dealer.deliveryAddress': 'Delivery Address',
    'dealer.pending': 'Pending',
    'dealer.confirmed': 'Confirmed',
    'dealer.shipped': 'Shipped',
    'dealer.delivered': 'Delivered',
    'dealer.cancelled': 'Cancelled',
    'dealer.paid': 'Paid',
    'dealer.unpaid': 'Unpaid',
    'dealer.noOrders': 'No orders found',
    
    // Voice
    'voice.tapToSpeak': 'Tap to speak',
    'voice.voiceNav': 'Voice',
    'voice.navigating': 'Navigating...',
    'voice.notUnderstood': 'Command not recognized',
    'voice.error': 'Voice recognition error',
    'voice.errorDesc': 'Please try again or check microphone permissions',
    'voice.notSupported': 'Voice not supported',
    'voice.notSupportedDesc': 'Your browser does not support voice recognition',
    'voice.listen': 'Listen',
    'voice.stop': 'Stop',
    'voice.listening': 'Listening...',
    'voice.startListening': 'Start voice input',
    'voice.stopListening': 'Stop voice input',
    'voice.speakResults': 'Listen to Results',
    
    // Chatbot
    'chatbot.subtitle': 'Your Agricultural Assistant',
    'chatbot.placeholder': 'Ask about crops, diseases, prices...',
  },
  
  hi: {
    // Navigation
    'nav.home': 'होम',
    'nav.dashboard': 'डैशबोर्ड',
    'nav.cropScan': 'फसल स्कैन',
    'nav.yieldPrediction': 'उपज अनुमान',
    'nav.marketPrices': 'बाज़ार भाव',
    'nav.nearbyMarkets': 'नज़दीकी मंडी',
    'nav.policies': 'सरकारी योजनाएं',
    'nav.login': 'लॉगिन',
    'nav.logout': 'लॉगआउट',
    
    // Landing Page
    'landing.hero.title': 'बेहतर कल के लिए स्मार्ट खेती',
    'landing.hero.subtitle': 'अपनी उपज को अधिकतम करने, फसल रोगों का जल्दी पता लगाने और वास्तविक समय की बाज़ार जानकारी प्राप्त करने के लिए AI-संचालित कृषि समाधान।',
    'landing.hero.getStarted': 'मुफ्त शुरू करें',
    'landing.hero.learnMore': 'और जानें',
    'landing.features.title': 'आधुनिक किसानों के लिए शक्तिशाली सुविधाएं',
    'landing.features.subtitle': 'आपकी खेती को बेहतर बनाने के लिए सब कुछ',
    'landing.cropScan.title': 'AI फसल रोग पहचान',
    'landing.cropScan.desc': 'अपनी फसलों की तस्वीरें अपलोड करें और उपचार सिफारिशों के साथ तुरंत AI-संचालित रोग निदान प्राप्त करें।',
    'landing.yield.title': 'उपज अनुमान',
    'landing.yield.desc': 'अपनी फसल के प्रकार, मिट्टी की स्थिति और खेती के तरीकों के आधार पर सटीक उपज अनुमान प्राप्त करें।',
    'landing.market.title': 'लाइव बाज़ार भाव',
    'landing.market.desc': 'भारत की विभिन्न मंडियों में कृषि वस्तुओं के वास्तविक समय के भाव देखें।',
    'landing.nearby.title': 'नज़दीकी मंडी खोजें',
    'landing.nearby.desc': 'संपर्क विवरण और उपलब्ध फसलों के साथ अपने पास की कृषि मंडियां खोजें।',
    'landing.policy.title': 'सरकारी योजनाएं',
    'landing.policy.desc': 'किसानों के लिए नवीनतम सरकारी नीतियों और सब्सिडी से अपडेट रहें।',
    'landing.chat.title': 'AI खेती सहायक',
    'landing.chat.desc': 'हमारे AI-संचालित चैटबॉट से अपने खेती के सवालों के तुरंत जवाब पाएं।',
    'landing.cta.title': 'अपनी खेती को बदलने के लिए तैयार हैं?',
    'landing.cta.subtitle': 'हज़ारों किसानों में शामिल हों जो पहले से ही FarmGenius का उपयोग करके अपनी उपज बढ़ा रहे हैं।',
    'landing.cta.button': 'अपनी यात्रा शुरू करें',
    
    // Dashboard
    'dashboard.welcome': 'स्वागत है',
    'dashboard.subtitle': 'आज आपके खेत में क्या हो रहा है',
    'dashboard.weather': 'आज का मौसम',
    'dashboard.tips': 'कृषि टिप्स',
    'dashboard.quickStats': 'त्वरित आंकड़े',
    'dashboard.cropScans': 'फसल स्कैन',
    'dashboard.predictions': 'अनुमान',
    'dashboard.markets': 'मंडियां',
    'dashboard.nearbyMarkets': 'नज़दीकी मंडियां',
    'dashboard.farmer': 'किसान',
    'dashboard.sunny': 'धूप',
    'dashboard.viewNotifications': 'सूचनाएं देखें',
    'dashboard.updateProfile': 'प्रोफ़ाइल अपडेट करें',
    'dashboard.scanNow': 'अभी स्कैन करें',
    'dashboard.predictNow': 'अभी अनुमान लगाएं',
    'dashboard.viewPrices': 'भाव देखें',
    'dashboard.findMarkets': 'मंडी खोजें',
    'dashboard.weatherForecast': '7-दिन का मौसम पूर्वानुमान',
    'dashboard.today': 'आज',
    'dashboard.tue': 'मंगल',
    'dashboard.wed': 'बुध',
    'dashboard.thu': 'गुरु',
    'dashboard.fri': 'शुक्र',
    'dashboard.sat': 'शनि',
    'dashboard.sun': 'रवि',
    'dashboard.wind': 'हवा',
    'dashboard.humidity': 'नमी',
    'dashboard.uvIndex': 'यूवी इंडेक्स',
    'dashboard.tipsAlerts': 'टिप्स और अलर्ट',
    'dashboard.readMore': 'और पढ़ें',
    'dashboard.avgWheatPrice': 'औसत गेहूं भाव',
    
    // Crop Scan
    'cropScan.title': 'AI फसल रोग पहचान',
    'cropScan.subtitle': 'रोगों का पता लगाने और उपचार सिफारिशें प्राप्त करने के लिए अपनी फसल की तस्वीर अपलोड करें',
    'cropScan.upload': 'छवि अपलोड करें',
    'cropScan.dragDrop': 'यहां छवि खींचें और छोड़ें, या चुनने के लिए क्लिक करें',
    'cropScan.analyzing': 'विश्लेषण हो रहा है...',
    'cropScan.analyze': 'फसल का विश्लेषण करें',
    'cropScan.results': 'विश्लेषण परिणाम',
    'cropScan.disease': 'रोग पाया गया',
    'cropScan.confidence': 'विश्वास स्तर',
    'cropScan.recommendations': 'सिफारिशें',
    'cropScan.history': 'पिछले स्कैन',
    
    // Yield Prediction
    'yield.title': 'फसल उपज अनुमान',
    'yield.subtitle': 'अपनी फसलों के लिए AI-संचालित उपज अनुमान प्राप्त करें',
    'yield.cropType': 'फसल का प्रकार',
    'yield.soilType': 'मिट्टी का प्रकार',
    'yield.area': 'क्षेत्रफल (एकड़)',
    'yield.sowingDate': 'बुवाई की तारीख',
    'yield.irrigation': 'सिंचाई का प्रकार',
    'yield.fertilizer': 'उपयोग किया गया उर्वरक',
    'yield.predict': 'उपज का अनुमान लगाएं',
    'yield.predicting': 'अनुमान लगाया जा रहा है...',
    'yield.results': 'अनुमान परिणाम',
    'yield.estimatedYield': 'अनुमानित उपज',
    'yield.revenue': 'अपेक्षित आय',
    'yield.harvestDays': 'कटाई तक के दिन',
    
    // Crops
    'crops.wheat': 'गेहूं',
    'crops.rice': 'धान (चावल)',
    'crops.maize': 'मक्का',
    'crops.potato': 'आलू',
    'crops.cotton': 'कपास',
    
    // Soil
    'soil.loamy': 'दोमट मिट्टी',
    'soil.sandy': 'रेतीली मिट्टी',
    'soil.clay': 'चिकनी मिट्टी',
    'soil.silty': 'गाद वाली मिट्टी',
    'soil.black': 'काली मिट्टी',
    
    // Irrigation
    'irrigation.drip': 'ड्रिप सिंचाई',
    'irrigation.sprinkler': 'छिड़काव सिंचाई',
    'irrigation.flood': 'बाढ़ सिंचाई',
    'irrigation.rainfed': 'वर्षा आधारित',
    
    // Fertilizer
    'fertilizer.urea': 'यूरिया',
    'fertilizer.organic': 'जैविक खाद',
    'fertilizer.mixed': 'मिश्रित खाद',
    
    // Market Prices
    'market.title': 'बाज़ार भाव',
    'market.subtitle': 'कृषि वस्तुओं के वास्तविक समय के भाव',
    'market.search': 'फसलें खोजें...',
    'market.filter': 'मंडी के अनुसार फ़िल्टर करें',
    'market.allMarkets': 'सभी मंडियां',
    'market.crop': 'फसल',
    'market.variety': 'किस्म',
    'market.price': 'भाव (₹/क्विंटल)',
    'market.trend': 'रुझान',
    'market.location': 'स्थान',
    
    // Nearby Markets
    'nearby.title': 'नज़दीकी मंडियां',
    'nearby.subtitle': 'अपने स्थान के पास कृषि मंडियां खोजें',
    'nearby.search': 'मंडियां खोजें...',
    'nearby.call': 'कॉल करें',
    'nearby.directions': 'दिशा-निर्देश पाएं',
    'nearby.crops': 'उपलब्ध फसलें',
    'nearby.hours': 'खुलने का समय',
    'nearby.rating': 'रेटिंग',
    
    // Policies
    'policies.title': 'सरकारी नीतियां और योजनाएं',
    'policies.subtitle': 'नवीनतम कृषि नीतियों से अपडेट रहें',
    'policies.search': 'नीतियां खोजें...',
    'policies.all': 'सभी',
    'policies.subsidy': 'सब्सिडी',
    'policies.insurance': 'बीमा',
    'policies.loan': 'ऋण',
    'policies.support': 'सहायता',
    'policies.readMore': 'और पढ़ें',
    
    // Auth
    'auth.login': 'लॉगिन',
    'auth.signup': 'साइन अप',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.fullName': 'पूरा नाम',
    'auth.phone': 'फोन नंबर',
    'auth.village': 'गांव/शहर',
    'auth.role': 'मैं हूं',
    'auth.farmer': 'किसान',
    'auth.dealer': 'व्यापारी',
    'auth.loginButton': 'लॉगिन करें',
    'auth.signupButton': 'खाता बनाएं',
    'auth.noAccount': 'खाता नहीं है?',
    'auth.hasAccount': 'पहले से खाता है?',
    
    // Chat
    'chat.title': 'FarmGenius AI',
    'chat.placeholder': 'खेती के बारे में पूछें...',
    'chat.send': 'भेजें',
    'chat.greeting': 'नमस्ते! मैं आपका AI खेती सहायक हूं। आज मैं आपकी कैसे मदद कर सकता हूं?',
    
    // Footer
    'footer.quickLinks': 'त्वरित लिंक',
    'footer.helpSupport': 'सहायता और समर्थन',
    'footer.contactUs': 'संपर्क करें',
    'footer.faq': 'सामान्य प्रश्न',
    'footer.tutorials': 'ट्यूटोरियल',
    'footer.feedback': 'प्रतिक्रिया',
    'footer.privacy': 'गोपनीयता नीति',
    'footer.terms': 'सेवा की शर्तें',
    'footer.rights': 'सर्वाधिकार सुरक्षित।',
    'footer.tagline': 'बेहतर फसल प्रबंधन, रोग पहचान और बाज़ार जानकारी के लिए AI-संचालित अंतर्दृष्टि के साथ किसानों को सशक्त बनाना।',
    
    // Stats
    'stats.farmersHelped': 'किसानों की मदद की',
    'stats.accuracy': 'पहचान सटीकता',
    'stats.marketsListed': 'मंडियां सूचीबद्ध',
    'stats.aiSupport': 'AI सहायता',
    
    // Benefits
    'benefits.title': 'किसान FarmGenius क्यों चुनते हैं',
    'benefits.subtitle': 'हज़ारों किसानों में शामिल हों जो पहले से ही AI का उपयोग करके अपनी फसल उपज बढ़ा रहे हैं।',
    'benefits.free': 'सभी किसानों के लिए मुफ्त',
    'benefits.languages': 'कई भारतीय भाषाओं में उपलब्ध',
    'benefits.noExpertise': 'तकनीकी विशेषज्ञता की आवश्यकता नहीं',
    'benefits.experts': 'कृषि विशेषज्ञों द्वारा समर्थित',
    'benefits.updates': 'नई सुविधाओं के साथ नियमित अपडेट',
    'benefits.community': 'समुदाय समर्थन और फ़ोरम',
    'benefits.startButton': 'FarmGenius का उपयोग शुरू करें',
    'benefits.smartAg': 'स्मार्ट कृषि',
    'benefits.poweredByAI': 'AI द्वारा संचालित',
    
    // Hero badge
    'landing.hero.badge': 'AI-संचालित कृषि समाधान',
    
    // Common
    'common.loading': 'लोड हो रहा है...',
    'common.error': 'एक त्रुटि हुई',
    'common.save': 'सहेजें',
    'common.cancel': 'रद्द करें',
    'common.delete': 'हटाएं',
    'common.edit': 'संपादित करें',
    'common.view': 'देखें',
    'common.back': 'वापस',
    'common.next': 'आगे',
    'common.submit': 'जमा करें',
    'common.search': 'खोजें',
    
    // Profile
    'profile.title': 'मेरी प्रोफ़ाइल',
    'profile.subtitle': 'अपनी व्यक्तिगत जानकारी अपडेट करें',
    'profile.email': 'ईमेल',
    'profile.emailHint': 'ईमेल बदला नहीं जा सकता',
    'profile.fullName': 'पूरा नाम',
    'profile.fullNamePlaceholder': 'अपना पूरा नाम दर्ज करें',
    'profile.phone': 'फोन नंबर',
    'profile.phonePlaceholder': 'अपना फोन नंबर दर्ज करें',
    'profile.village': 'गांव/शहर',
    'profile.villagePlaceholder': 'अपना गांव या शहर दर्ज करें',
    'profile.save': 'बदलाव सहेजें',
    'profile.saving': 'सहेजा जा रहा है...',
    'profile.success': 'प्रोफ़ाइल सफलतापूर्वक अपडेट हुई!',
    'profile.error': 'प्रोफ़ाइल अपडेट करने में विफल। कृपया पुनः प्रयास करें।',
    'profile.changePhoto': 'फ़ोटो बदलें',
    'profile.uploadingPhoto': 'अपलोड हो रहा है...',
    'profile.photoSuccess': 'फ़ोटो सफलतापूर्वक अपडेट हुई!',
    'profile.photoError': 'फ़ोटो अपलोड करने में विफल। कृपया पुनः प्रयास करें।',
    
    // Dealer
    'dealer.dashboard': 'व्यापारी डैशबोर्ड',
    'dealer.welcome': 'स्वागत है',
    'dealer.subtitle': 'अपने व्यापारिक कार्यों को अपने डैशबोर्ड से प्रबंधित करें',
    'dealer.buyOffers': 'खरीद प्रस्ताव',
    'dealer.buyOffersDesc': 'किसानों से अपनी मनचाही कीमत पर फसल खरीदने के लिए प्रस्ताव पोस्ट करें',
    'dealer.farmerDirectory': 'किसान निर्देशिका',
    'dealer.farmerDirectoryDesc': 'अपने क्षेत्र के किसानों को ब्राउज़ करें और संपर्क करें',
    'dealer.inventory': 'इन्वेंटरी',
    'dealer.inventoryDesc': 'खरीदी गई फसलों को ट्रैक करें और अपना स्टॉक प्रबंधित करें',
    'dealer.orders': 'ऑर्डर',
    'dealer.ordersDesc': 'ऑर्डर, डिलीवरी और भुगतान प्रबंधित करें',
    'dealer.activeOffers': 'सक्रिय प्रस्ताव',
    'dealer.quintalsInStock': 'स्टॉक में क्विंटल',
    'dealer.pendingOrders': 'लंबित ऑर्डर',
    'dealer.completed': 'पूर्ण',
    'dealer.quickActions': 'त्वरित कार्रवाई',
    'dealer.postNewOffer': 'नया खरीद प्रस्ताव पोस्ट करें',
    'dealer.addInventory': 'इन्वेंटरी जोड़ें',
    'dealer.checkPrices': 'बाज़ार भाव देखें',
    'dealer.newOffer': 'नया प्रस्ताव',
    'dealer.createOffer': 'खरीद प्रस्ताव बनाएं',
    'dealer.editOffer': 'प्रस्ताव संपादित करें',
    'dealer.crop': 'फसल',
    'dealer.variety': 'किस्म',
    'dealer.quantity': 'मात्रा (क्विंटल)',
    'dealer.pricePerQuintal': 'भाव (₹/क्विंटल)',
    'dealer.location': 'स्थान',
    'dealer.description': 'विवरण',
    'dealer.status': 'स्थिति',
    'dealer.active': 'सक्रिय',
    'dealer.closed': 'बंद',
    'dealer.expired': 'समाप्त',
    'dealer.closeOffer': 'प्रस्ताव बंद करें',
    'dealer.reactivate': 'पुनः सक्रिय करें',
    'dealer.noOffers': 'कोई खरीद प्रस्ताव नहीं मिला',
    'dealer.createFirst': 'अपना पहला प्रस्ताव बनाएं',
    'dealer.browseFarmers': 'किसान ब्राउज़ करें',
    'dealer.searchFarmers': 'नाम या स्थान से किसान खोजें...',
    'dealer.noFarmers': 'कोई किसान नहीं मिला',
    'dealer.contact': 'संपर्क',
    'dealer.call': 'कॉल करें',
    'dealer.addToInventory': 'इन्वेंटरी में जोड़ें',
    'dealer.farmerName': 'किसान का नाम',
    'dealer.purchaseDate': 'खरीद तिथि',
    'dealer.purchasePrice': 'खरीद मूल्य',
    'dealer.notes': 'नोट्स',
    'dealer.noInventory': 'कोई इन्वेंटरी आइटम नहीं',
    'dealer.createOrder': 'ऑर्डर बनाएं',
    'dealer.orderDetails': 'ऑर्डर विवरण',
    'dealer.totalAmount': 'कुल राशि',
    'dealer.paymentStatus': 'भुगतान स्थिति',
    'dealer.deliveryAddress': 'डिलीवरी पता',
    'dealer.pending': 'लंबित',
    'dealer.confirmed': 'पुष्टि',
    'dealer.shipped': 'भेजा गया',
    'dealer.delivered': 'डिलीवर',
    'dealer.cancelled': 'रद्द',
    'dealer.paid': 'भुगतान हुआ',
    'dealer.unpaid': 'बकाया',
    'dealer.noOrders': 'कोई ऑर्डर नहीं मिला',
    
    // Voice
    'voice.tapToSpeak': 'बोलने के लिए टैप करें',
    'voice.voiceNav': 'आवाज़',
    'voice.navigating': 'नेविगेट हो रहा है...',
    'voice.notUnderstood': 'कमांड समझ नहीं आई',
    'voice.error': 'आवाज़ पहचान त्रुटि',
    'voice.errorDesc': 'कृपया पुनः प्रयास करें या माइक्रोफ़ोन अनुमति जाँचें',
    'voice.notSupported': 'आवाज़ समर्थित नहीं',
    'voice.notSupportedDesc': 'आपका ब्राउज़र आवाज़ पहचान का समर्थन नहीं करता',
    'voice.listen': 'सुनें',
    'voice.stop': 'रोकें',
    'voice.listening': 'सुन रहे हैं...',
    'voice.startListening': 'आवाज़ इनपुट शुरू करें',
    'voice.stopListening': 'आवाज़ इनपुट रोकें',
    'voice.speakResults': 'परिणाम सुनें',
    
    // Chatbot
    'chatbot.subtitle': 'आपका कृषि सहायक',
    'chatbot.placeholder': 'फसल, रोग, भाव के बारे में पूछें...',
  },
  
  mr: {
    // Navigation
    'nav.home': 'मुख्यपृष्ठ',
    'nav.dashboard': 'डॅशबोर्ड',
    'nav.cropScan': 'पीक स्कॅन',
    'nav.yieldPrediction': 'उत्पादन अंदाज',
    'nav.marketPrices': 'बाजारभाव',
    'nav.nearbyMarkets': 'जवळची बाजारपेठ',
    'nav.policies': 'सरकारी योजना',
    'nav.login': 'लॉगिन',
    'nav.logout': 'लॉगआउट',
    
    // Landing Page
    'landing.hero.title': 'उद्याच्या उत्तम शेतीसाठी स्मार्ट शेती',
    'landing.hero.subtitle': 'तुमचे उत्पादन वाढवण्यासाठी, पीक रोग लवकर शोधण्यासाठी आणि रिअल-टाइम बाजार माहिती मिळवण्यासाठी AI-संचालित कृषी उपाय.',
    'landing.hero.getStarted': 'मोफत सुरू करा',
    'landing.hero.learnMore': 'अधिक जाणून घ्या',
    'landing.features.title': 'आधुनिक शेतकऱ्यांसाठी शक्तिशाली वैशिष्ट्ये',
    'landing.features.subtitle': 'तुमची शेती सुधारण्यासाठी आवश्यक सर्व काही',
    'landing.cropScan.title': 'AI पीक रोग ओळख',
    'landing.cropScan.desc': 'तुमच्या पिकांचे फोटो अपलोड करा आणि उपचार शिफारशींसह त्वरित AI-संचालित रोग निदान मिळवा.',
    'landing.yield.title': 'उत्पादन अंदाज',
    'landing.yield.desc': 'तुमच्या पीक प्रकार, माती स्थिती आणि शेती पद्धतींवर आधारित अचूक उत्पादन अंदाज मिळवा.',
    'landing.market.title': 'लाइव्ह बाजारभाव',
    'landing.market.desc': 'भारतातील विविध बाजारपेठांमध्ये कृषी मालाचे रिअल-टाइम भाव पहा.',
    'landing.nearby.title': 'जवळच्या बाजारपेठा शोधा',
    'landing.nearby.desc': 'संपर्क तपशील आणि उपलब्ध पिकांसह तुमच्या जवळील कृषी बाजारपेठा शोधा.',
    'landing.policy.title': 'सरकारी योजना',
    'landing.policy.desc': 'शेतकऱ्यांसाठी नवीनतम सरकारी धोरणे आणि अनुदानांची माहिती घ्या.',
    'landing.chat.title': 'AI शेती सहाय्यक',
    'landing.chat.desc': 'आमच्या AI-संचालित चॅटबॉटकडून तुमच्या शेतीच्या प्रश्नांची त्वरित उत्तरे मिळवा.',
    'landing.cta.title': 'तुमची शेती बदलण्यासाठी तयार आहात?',
    'landing.cta.subtitle': 'हजारो शेतकऱ्यांमध्ये सामील व्हा जे आधीच FarmGenius वापरून त्यांचे उत्पादन सुधारत आहेत.',
    'landing.cta.button': 'तुमचा प्रवास सुरू करा',
    
    // Dashboard
    'dashboard.welcome': 'स्वागत आहे',
    'dashboard.subtitle': 'आज तुमच्या शेतात काय चालू आहे',
    'dashboard.weather': 'आजचे हवामान',
    'dashboard.tips': 'कृषी टिप्स',
    'dashboard.quickStats': 'जलद आकडेवारी',
    'dashboard.cropScans': 'पीक स्कॅन',
    'dashboard.predictions': 'अंदाज',
    'dashboard.markets': 'बाजारपेठा',
    'dashboard.nearbyMarkets': 'जवळची बाजारपेठ',
    'dashboard.farmer': 'शेतकरी',
    'dashboard.sunny': 'सनी',
    'dashboard.viewNotifications': 'सूचना पहा',
    'dashboard.updateProfile': 'प्रोफाइल अपडेट करा',
    'dashboard.scanNow': 'आता स्कॅन करा',
    'dashboard.predictNow': 'आता अंदाज लावा',
    'dashboard.viewPrices': 'भाव पहा',
    'dashboard.findMarkets': 'बाजारपेठ शोधा',
    'dashboard.weatherForecast': '7-दिवसांचा हवामान अंदाज',
    'dashboard.today': 'आज',
    'dashboard.tue': 'मंगळ',
    'dashboard.wed': 'बुध',
    'dashboard.thu': 'गुरु',
    'dashboard.fri': 'शुक्र',
    'dashboard.sat': 'शनि',
    'dashboard.sun': 'रवि',
    'dashboard.wind': 'वारा',
    'dashboard.humidity': 'आर्द्रता',
    'dashboard.uvIndex': 'यूव्ही इंडेक्स',
    'dashboard.tipsAlerts': 'टिप्स आणि अलर्ट',
    'dashboard.readMore': 'अधिक वाचा',
    'dashboard.avgWheatPrice': 'सरासरी गहू भाव',
    
    // Crop Scan
    'cropScan.title': 'AI पीक रोग ओळख',
    'cropScan.subtitle': 'रोग शोधण्यासाठी आणि उपचार शिफारशी मिळवण्यासाठी तुमच्या पिकाचा फोटो अपलोड करा',
    'cropScan.upload': 'प्रतिमा अपलोड करा',
    'cropScan.dragDrop': 'येथे प्रतिमा ड्रॅग आणि ड्रॉप करा, किंवा निवडण्यासाठी क्लिक करा',
    'cropScan.analyzing': 'विश्लेषण होत आहे...',
    'cropScan.analyze': 'पिकाचे विश्लेषण करा',
    'cropScan.results': 'विश्लेषण निकाल',
    'cropScan.disease': 'रोग आढळला',
    'cropScan.confidence': 'विश्वास पातळी',
    'cropScan.recommendations': 'शिफारशी',
    'cropScan.history': 'मागील स्कॅन',
    
    // Yield Prediction
    'yield.title': 'पीक उत्पादन अंदाज',
    'yield.subtitle': 'तुमच्या पिकांसाठी AI-संचालित उत्पादन अंदाज मिळवा',
    'yield.cropType': 'पीक प्रकार',
    'yield.soilType': 'माती प्रकार',
    'yield.area': 'क्षेत्रफळ (एकर)',
    'yield.sowingDate': 'पेरणी तारीख',
    'yield.irrigation': 'सिंचन प्रकार',
    'yield.fertilizer': 'वापरलेले खत',
    'yield.predict': 'उत्पादन अंदाज करा',
    'yield.predicting': 'अंदाज केला जात आहे...',
    'yield.results': 'अंदाज निकाल',
    'yield.estimatedYield': 'अंदाजित उत्पादन',
    'yield.revenue': 'अपेक्षित उत्पन्न',
    'yield.harvestDays': 'काढणीपर्यंत दिवस',
    
    // Crops
    'crops.wheat': 'गहू',
    'crops.rice': 'भात (तांदूळ)',
    'crops.maize': 'मका',
    'crops.potato': 'बटाटा',
    'crops.cotton': 'कापूस',
    
    // Soil
    'soil.loamy': 'लोमी माती',
    'soil.sandy': 'रेताड माती',
    'soil.clay': 'चिकण माती',
    'soil.silty': 'गाळाची माती',
    'soil.black': 'काळी माती',
    
    // Irrigation
    'irrigation.drip': 'ठिबक सिंचन',
    'irrigation.sprinkler': 'तुषार सिंचन',
    'irrigation.flood': 'पाट पाणी',
    'irrigation.rainfed': 'कोरडवाहू',
    
    // Fertilizer
    'fertilizer.urea': 'युरिया',
    'fertilizer.organic': 'सेंद्रिय खत',
    'fertilizer.mixed': 'मिश्रित खत',
    
    // Market Prices
    'market.title': 'बाजारभाव',
    'market.subtitle': 'कृषी मालाचे रिअल-टाइम भाव',
    'market.search': 'पिके शोधा...',
    'market.filter': 'बाजारपेठेनुसार फिल्टर करा',
    'market.allMarkets': 'सर्व बाजारपेठा',
    'market.crop': 'पीक',
    'market.variety': 'प्रकार',
    'market.price': 'भाव (₹/क्विंटल)',
    'market.trend': 'कल',
    'market.location': 'स्थान',
    
    // Nearby Markets
    'nearby.title': 'जवळच्या बाजारपेठा',
    'nearby.subtitle': 'तुमच्या स्थानाजवळ कृषी बाजारपेठा शोधा',
    'nearby.search': 'बाजारपेठा शोधा...',
    'nearby.call': 'कॉल करा',
    'nearby.directions': 'दिशानिर्देश मिळवा',
    'nearby.crops': 'उपलब्ध पिके',
    'nearby.hours': 'उघडण्याची वेळ',
    'nearby.rating': 'रेटिंग',
    
    // Policies
    'policies.title': 'सरकारी धोरणे आणि योजना',
    'policies.subtitle': 'नवीनतम कृषी धोरणांची माहिती घ्या',
    'policies.search': 'धोरणे शोधा...',
    'policies.all': 'सर्व',
    'policies.subsidy': 'अनुदान',
    'policies.insurance': 'विमा',
    'policies.loan': 'कर्ज',
    'policies.support': 'सहाय्य',
    'policies.readMore': 'अधिक वाचा',
    
    // Auth
    'auth.login': 'लॉगिन',
    'auth.signup': 'साइन अप',
    'auth.email': 'ईमेल',
    'auth.password': 'पासवर्ड',
    'auth.fullName': 'पूर्ण नाव',
    'auth.phone': 'फोन नंबर',
    'auth.village': 'गाव/शहर',
    'auth.role': 'मी आहे',
    'auth.farmer': 'शेतकरी',
    'auth.dealer': 'व्यापारी',
    'auth.loginButton': 'लॉगिन करा',
    'auth.signupButton': 'खाते तयार करा',
    'auth.noAccount': 'खाते नाही?',
    'auth.hasAccount': 'आधीच खाते आहे?',
    
    // Chat
    'chat.title': 'FarmGenius AI',
    'chat.placeholder': 'शेतीबद्दल विचारा...',
    'chat.send': 'पाठवा',
    'chat.greeting': 'नमस्कार! मी तुमचा AI शेती सहाय्यक आहे. आज मी तुमची कशी मदत करू शकतो?',
    
    // Footer
    'footer.quickLinks': 'जलद दुवे',
    'footer.helpSupport': 'मदत आणि समर्थन',
    'footer.contactUs': 'संपर्क साधा',
    'footer.faq': 'वारंवार विचारले जाणारे प्रश्न',
    'footer.tutorials': 'ट्युटोरियल',
    'footer.feedback': 'अभिप्राय',
    'footer.privacy': 'गोपनीयता धोरण',
    'footer.terms': 'सेवा अटी',
    'footer.rights': 'सर्व हक्क राखीव.',
    'footer.tagline': 'उत्तम पीक व्यवस्थापन, रोग ओळख आणि बाजार माहितीसाठी AI-संचालित अंतर्दृष्टीने शेतकऱ्यांना सक्षम करणे.',
    
    // Stats
    'stats.farmersHelped': 'शेतकऱ्यांना मदत केली',
    'stats.accuracy': 'ओळख अचूकता',
    'stats.marketsListed': 'बाजारपेठा सूचीबद्ध',
    'stats.aiSupport': 'AI समर्थन',
    
    // Benefits
    'benefits.title': 'शेतकरी FarmGenius का निवडतात',
    'benefits.subtitle': 'आधीच AI वापरून त्यांचे पीक उत्पादन सुधारत असलेल्या हजारो शेतकऱ्यांमध्ये सामील व्हा.',
    'benefits.free': 'सर्व शेतकऱ्यांसाठी मोफत',
    'benefits.languages': 'अनेक भारतीय भाषांमध्ये उपलब्ध',
    'benefits.noExpertise': 'तांत्रिक कौशल्य आवश्यक नाही',
    'benefits.experts': 'कृषी तज्ञांचे समर्थन',
    'benefits.updates': 'नवीन वैशिष्ट्यांसह नियमित अपडेट',
    'benefits.community': 'समुदाय समर्थन आणि मंच',
    'benefits.startButton': 'FarmGenius वापरणे सुरू करा',
    'benefits.smartAg': 'स्मार्ट शेती',
    'benefits.poweredByAI': 'AI द्वारे संचालित',
    
    // Hero badge
    'landing.hero.badge': 'AI-संचालित कृषी उपाय',
    'common.error': 'एक त्रुटी आली',
    'common.save': 'जतन करा',
    'common.cancel': 'रद्द करा',
    'common.delete': 'हटवा',
    'common.edit': 'संपादित करा',
    'common.view': 'पहा',
    'common.back': 'मागे',
    'common.next': 'पुढे',
    'common.submit': 'सबमिट करा',
    'common.search': 'शोधा',
    
    // Profile
    'profile.title': 'माझी प्रोफाइल',
    'profile.subtitle': 'तुमची वैयक्तिक माहिती अपडेट करा',
    'profile.email': 'ईमेल',
    'profile.emailHint': 'ईमेल बदलता येत नाही',
    'profile.fullName': 'पूर्ण नाव',
    'profile.fullNamePlaceholder': 'तुमचे पूर्ण नाव प्रविष्ट करा',
    'profile.phone': 'फोन नंबर',
    'profile.phonePlaceholder': 'तुमचा फोन नंबर प्रविष्ट करा',
    'profile.village': 'गाव/शहर',
    'profile.villagePlaceholder': 'तुमचे गाव किंवा शहर प्रविष्ट करा',
    'profile.save': 'बदल जतन करा',
    'profile.saving': 'जतन होत आहे...',
    'profile.success': 'प्रोफाइल यशस्वीरित्या अपडेट झाली!',
    'profile.error': 'प्रोफाइल अपडेट करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
    'profile.changePhoto': 'फोटो बदला',
    'profile.uploadingPhoto': 'अपलोड होत आहे...',
    'profile.photoSuccess': 'फोटो यशस्वीरित्या अपडेट झाला!',
    'profile.photoError': 'फोटो अपलोड करण्यात अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
    
    // Dealer
    'dealer.dashboard': 'व्यापारी डॅशबोर्ड',
    'dealer.welcome': 'स्वागत आहे',
    'dealer.subtitle': 'तुमच्या व्यापारी डॅशबोर्डवरून व्यापार व्यवस्थापित करा',
    'dealer.buyOffers': 'खरेदी ऑफर',
    'dealer.buyOffersDesc': 'शेतकऱ्यांकडून तुमच्या इच्छित किंमतीला पीक खरेदी करण्यासाठी ऑफर पोस्ट करा',
    'dealer.farmerDirectory': 'शेतकरी निर्देशिका',
    'dealer.farmerDirectoryDesc': 'तुमच्या भागातील शेतकऱ्यांना ब्राउझ करा आणि संपर्क साधा',
    'dealer.inventory': 'इन्व्हेंटरी',
    'dealer.inventoryDesc': 'खरेदी केलेल्या पिकांचा मागोवा घ्या आणि तुमचा साठा व्यवस्थापित करा',
    'dealer.orders': 'ऑर्डर',
    'dealer.ordersDesc': 'ऑर्डर, डिलिव्हरी आणि पेमेंट व्यवस्थापित करा',
    'dealer.activeOffers': 'सक्रिय ऑफर',
    'dealer.quintalsInStock': 'साठ्यात क्विंटल',
    'dealer.pendingOrders': 'प्रलंबित ऑर्डर',
    'dealer.completed': 'पूर्ण',
    'dealer.quickActions': 'जलद क्रिया',
    'dealer.postNewOffer': 'नवीन खरेदी ऑफर पोस्ट करा',
    'dealer.addInventory': 'इन्व्हेंटरी जोडा',
    'dealer.checkPrices': 'बाजारभाव तपासा',
    'dealer.newOffer': 'नवीन ऑफर',
    'dealer.createOffer': 'खरेदी ऑफर तयार करा',
    'dealer.editOffer': 'ऑफर संपादित करा',
    'dealer.crop': 'पीक',
    'dealer.variety': 'प्रकार',
    'dealer.quantity': 'प्रमाण (क्विंटल)',
    'dealer.pricePerQuintal': 'भाव (₹/क्विंटल)',
    'dealer.location': 'स्थान',
    'dealer.description': 'वर्णन',
    'dealer.status': 'स्थिती',
    'dealer.active': 'सक्रिय',
    'dealer.closed': 'बंद',
    'dealer.expired': 'कालबाह्य',
    'dealer.closeOffer': 'ऑफर बंद करा',
    'dealer.reactivate': 'पुन्हा सक्रिय करा',
    'dealer.noOffers': 'कोणतीही खरेदी ऑफर सापडली नाही',
    'dealer.createFirst': 'तुमची पहिली ऑफर तयार करा',
    'dealer.browseFarmers': 'शेतकरी ब्राउझ करा',
    'dealer.searchFarmers': 'नाव किंवा स्थानावरून शेतकरी शोधा...',
    'dealer.noFarmers': 'कोणताही शेतकरी सापडला नाही',
    'dealer.contact': 'संपर्क',
    'dealer.call': 'कॉल करा',
    'dealer.addToInventory': 'इन्व्हेंटरीमध्ये जोडा',
    'dealer.farmerName': 'शेतकऱ्याचे नाव',
    'dealer.purchaseDate': 'खरेदी तारीख',
    'dealer.purchasePrice': 'खरेदी किंमत',
    'dealer.notes': 'नोट्स',
    'dealer.noInventory': 'कोणतीही इन्व्हेंटरी आयटम नाही',
    'dealer.createOrder': 'ऑर्डर तयार करा',
    'dealer.orderDetails': 'ऑर्डर तपशील',
    'dealer.totalAmount': 'एकूण रक्कम',
    'dealer.paymentStatus': 'पेमेंट स्थिती',
    'dealer.deliveryAddress': 'डिलिव्हरी पत्ता',
    'dealer.pending': 'प्रलंबित',
    'dealer.confirmed': 'पुष्टी',
    'dealer.shipped': 'पाठवले',
    'dealer.delivered': 'वितरित',
    'dealer.cancelled': 'रद्द',
    'dealer.paid': 'पेमेंट झाले',
    'dealer.unpaid': 'बाकी',
    'dealer.noOrders': 'कोणताही ऑर्डर सापडला नाही',
    
    // Voice
    'voice.tapToSpeak': 'बोलण्यासाठी टॅप करा',
    'voice.voiceNav': 'आवाज',
    'voice.navigating': 'नेव्हिगेट होत आहे...',
    'voice.notUnderstood': 'आदेश समजला नाही',
    'voice.error': 'आवाज ओळख त्रुटी',
    'voice.errorDesc': 'कृपया पुन्हा प्रयत्न करा किंवा मायक्रोफोन परवानगी तपासा',
    'voice.notSupported': 'आवाज समर्थित नाही',
    'voice.notSupportedDesc': 'तुमचा ब्राउझर आवाज ओळखण्यास समर्थन देत नाही',
    'voice.listen': 'ऐका',
    'voice.stop': 'थांबा',
    'voice.listening': 'ऐकत आहे...',
    'voice.startListening': 'आवाज इनपुट सुरू करा',
    'voice.stopListening': 'आवाज इनपुट थांबवा',
    'voice.speakResults': 'निकाल ऐका',
    
    // Chatbot
    'chatbot.subtitle': 'तुमचा कृषी सहाय्यक',
    'chatbot.placeholder': 'पिके, रोग, भाव बद्दल विचारा...',
  },
  
  kn: {
    // Navigation
    'nav.home': 'ಮುಖಪುಟ',
    'nav.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'nav.cropScan': 'ಬೆಳೆ ಸ್ಕ್ಯಾನ್',
    'nav.yieldPrediction': 'ಇಳುವರಿ ಮುನ್ಸೂಚನೆ',
    'nav.marketPrices': 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆ',
    'nav.nearbyMarkets': 'ಹತ್ತಿರದ ಮಾರುಕಟ್ಟೆ',
    'nav.policies': 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    'nav.login': 'ಲಾಗಿನ್',
    'nav.logout': 'ಲಾಗ್ ಔಟ್',
    
    // Landing Page
    'landing.hero.title': 'ಉತ್ತಮ ನಾಳೆಗಾಗಿ ಸ್ಮಾರ್ಟ್ ಕೃಷಿ',
    'landing.hero.subtitle': 'ನಿಮ್ಮ ಇಳುವರಿಯನ್ನು ಗರಿಷ್ಠಗೊಳಿಸಲು, ಬೆಳೆ ರೋಗಗಳನ್ನು ಬೇಗನೆ ಪತ್ತೆಹಚ್ಚಲು ಮತ್ತು ರಿಯಲ್-ಟೈಮ್ ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿ ಪಡೆಯಲು AI-ಆಧಾರಿತ ಕೃಷಿ ಪರಿಹಾರಗಳು.',
    'landing.hero.getStarted': 'ಉಚಿತವಾಗಿ ಪ್ರಾರಂಭಿಸಿ',
    'landing.hero.learnMore': 'ಇನ್ನಷ್ಟು ತಿಳಿಯಿರಿ',
    'landing.features.title': 'ಆಧುನಿಕ ರೈತರಿಗೆ ಶಕ್ತಿಶಾಲಿ ವೈಶಿಷ್ಟ್ಯಗಳು',
    'landing.features.subtitle': 'ನಿಮ್ಮ ಕೃಷಿಯನ್ನು ಸುಧಾರಿಸಲು ಎಲ್ಲವೂ ಅಗತ್ಯ',
    'landing.cropScan.title': 'AI ಬೆಳೆ ರೋಗ ಪತ್ತೆ',
    'landing.cropScan.desc': 'ನಿಮ್ಮ ಬೆಳೆಗಳ ಫೋಟೋಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ಚಿಕಿತ್ಸೆ ಶಿಫಾರಸುಗಳೊಂದಿಗೆ ತಕ್ಷಣದ AI-ಆಧಾರಿತ ರೋಗ ಪತ್ತೆ ಪಡೆಯಿರಿ.',
    'landing.yield.title': 'ಇಳುವರಿ ಮುನ್ಸೂಚನೆ',
    'landing.yield.desc': 'ನಿಮ್ಮ ಬೆಳೆ ಪ್ರಕಾರ, ಮಣ್ಣಿನ ಸ್ಥಿತಿ ಮತ್ತು ಕೃಷಿ ಪದ್ಧತಿಗಳ ಆಧಾರದ ಮೇಲೆ ನಿಖರ ಇಳುವರಿ ಮುನ್ಸೂಚನೆಗಳನ್ನು ಪಡೆಯಿರಿ.',
    'landing.market.title': 'ಲೈವ್ ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
    'landing.market.desc': 'ಭಾರತದ ವಿವಿಧ ಮಾರುಕಟ್ಟೆಗಳಲ್ಲಿ ಕೃಷಿ ಸರಕುಗಳ ರಿಯಲ್-ಟೈಮ್ ಬೆಲೆಗಳನ್ನು ನೋಡಿ.',
    'landing.nearby.title': 'ಹತ್ತಿರದ ಮಾರುಕಟ್ಟೆಗಳನ್ನು ಹುಡುಕಿ',
    'landing.nearby.desc': 'ಸಂಪರ್ಕ ವಿವರಗಳು ಮತ್ತು ಲಭ್ಯವಿರುವ ಬೆಳೆಗಳೊಂದಿಗೆ ನಿಮ್ಮ ಬಳಿಯ ಕೃಷಿ ಮಾರುಕಟ್ಟೆಗಳನ್ನು ಹುಡುಕಿ.',
    'landing.policy.title': 'ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು',
    'landing.policy.desc': 'ರೈತರಿಗಾಗಿ ಇತ್ತೀಚಿನ ಸರ್ಕಾರಿ ನೀತಿಗಳು ಮತ್ತು ಸಬ್ಸಿಡಿಗಳ ಬಗ್ಗೆ ನವೀಕೃತವಾಗಿರಿ.',
    'landing.chat.title': 'AI ಕೃಷಿ ಸಹಾಯಕ',
    'landing.chat.desc': 'ನಮ್ಮ AI-ಆಧಾರಿತ ಚಾಟ್‌ಬಾಟ್‌ನಿಂದ ನಿಮ್ಮ ಕೃಷಿ ಪ್ರಶ್ನೆಗಳಿಗೆ ತಕ್ಷಣದ ಉತ್ತರಗಳನ್ನು ಪಡೆಯಿರಿ.',
    'landing.cta.title': 'ನಿಮ್ಮ ಕೃಷಿಯನ್ನು ಬದಲಾಯಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?',
    'landing.cta.subtitle': 'ಈಗಾಗಲೇ FarmGenius ಬಳಸಿ ತಮ್ಮ ಇಳುವರಿಯನ್ನು ಸುಧಾರಿಸುತ್ತಿರುವ ಸಾವಿರಾರು ರೈತರೊಂದಿಗೆ ಸೇರಿ.',
    'landing.cta.button': 'ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಪ್ರಾರಂಭಿಸಿ',
    
    // Dashboard
    'dashboard.welcome': 'ಸ್ವಾಗತ',
    'dashboard.subtitle': 'ಇಂದು ನಿಮ್ಮ ಹೊಲದಲ್ಲಿ ಏನು ನಡೆಯುತ್ತಿದೆ',
    'dashboard.weather': 'ಇಂದಿನ ಹವಾಮಾನ',
    'dashboard.tips': 'ಕೃಷಿ ಸಲಹೆಗಳು',
    'dashboard.quickStats': 'ತ್ವರಿತ ಅಂಕಿಅಂಶಗಳು',
    'dashboard.cropScans': 'ಬೆಳೆ ಸ್ಕ್ಯಾನ್',
    'dashboard.predictions': 'ಮುನ್ಸೂಚನೆಗಳು',
    'dashboard.markets': 'ಮಾರುಕಟ್ಟೆಗಳು',
    'dashboard.nearbyMarkets': 'ಹತ್ತಿರದ ಮಾರುಕಟ್ಟೆಗಳು',
    'dashboard.farmer': 'ರೈತ',
    'dashboard.sunny': 'ಬಿಸಿಲು',
    'dashboard.viewNotifications': 'ಅಧಿಸೂಚನೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    'dashboard.updateProfile': 'ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಿ',
    'dashboard.scanNow': 'ಈಗ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
    'dashboard.predictNow': 'ಈಗ ಮುನ್ಸೂಚನೆ ಮಾಡಿ',
    'dashboard.viewPrices': 'ಬೆಲೆಗಳನ್ನು ನೋಡಿ',
    'dashboard.findMarkets': 'ಮಾರುಕಟ್ಟೆಗಳನ್ನು ಹುಡುಕಿ',
    'dashboard.weatherForecast': '7-ದಿನಗಳ ಹವಾಮಾನ ಮುನ್ಸೂಚನೆ',
    'dashboard.today': 'ಇಂದು',
    'dashboard.tue': 'ಮಂಗಳ',
    'dashboard.wed': 'ಬುಧ',
    'dashboard.thu': 'ಗುರು',
    'dashboard.fri': 'ಶುಕ್ರ',
    'dashboard.sat': 'ಶನಿ',
    'dashboard.sun': 'ರವಿ',
    'dashboard.wind': 'ಗಾಳಿ',
    'dashboard.humidity': 'ಆರ್ದ್ರತೆ',
    'dashboard.uvIndex': 'ಯುವಿ ಇಂಡೆಕ್ಸ್',
    'dashboard.tipsAlerts': 'ಸಲಹೆಗಳು ಮತ್ತು ಎಚ್ಚರಿಕೆಗಳು',
    'dashboard.readMore': 'ಇನ್ನಷ್ಟು ಓದಿ',
    'dashboard.avgWheatPrice': 'ಸರಾಸರಿ ಗೋಧಿ ಬೆಲೆ',
    
    // Crop Scan
    'cropScan.title': 'AI ಬೆಳೆ ರೋಗ ಪತ್ತೆ',
    'cropScan.subtitle': 'ರೋಗಗಳನ್ನು ಪತ್ತೆಹಚ್ಚಲು ಮತ್ತು ಚಿಕಿತ್ಸೆ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ಬೆಳೆಯ ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'cropScan.upload': 'ಚಿತ್ರ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ',
    'cropScan.dragDrop': 'ಇಲ್ಲಿ ಚಿತ್ರವನ್ನು ಎಳೆದು ಬಿಡಿ, ಅಥವಾ ಆಯ್ಕೆ ಮಾಡಲು ಕ್ಲಿಕ್ ಮಾಡಿ',
    'cropScan.analyzing': 'ವಿಶ್ಲೇಷಣೆ ನಡೆಯುತ್ತಿದೆ...',
    'cropScan.analyze': 'ಬೆಳೆ ವಿಶ್ಲೇಷಿಸಿ',
    'cropScan.results': 'ವಿಶ್ಲೇಷಣೆ ಫಲಿತಾಂಶಗಳು',
    'cropScan.disease': 'ರೋಗ ಪತ್ತೆಯಾಗಿದೆ',
    'cropScan.confidence': 'ವಿಶ್ವಾಸ ಮಟ್ಟ',
    'cropScan.recommendations': 'ಶಿಫಾರಸುಗಳು',
    'cropScan.history': 'ಹಿಂದಿನ ಸ್ಕ್ಯಾನ್‌ಗಳು',
    
    // Yield Prediction
    'yield.title': 'ಬೆಳೆ ಇಳುವರಿ ಮುನ್ಸೂಚನೆ',
    'yield.subtitle': 'ನಿಮ್ಮ ಬೆಳೆಗಳಿಗೆ AI-ಆಧಾರಿತ ಇಳುವರಿ ಮುನ್ಸೂಚನೆಗಳನ್ನು ಪಡೆಯಿರಿ',
    'yield.cropType': 'ಬೆಳೆ ಪ್ರಕಾರ',
    'yield.soilType': 'ಮಣ್ಣಿನ ಪ್ರಕಾರ',
    'yield.area': 'ಪ್ರದೇಶ (ಎಕರೆ)',
    'yield.sowingDate': 'ಬಿತ್ತನೆ ದಿನಾಂಕ',
    'yield.irrigation': 'ನೀರಾವರಿ ಪ್ರಕಾರ',
    'yield.fertilizer': 'ಬಳಸಿದ ರಸಗೊಬ್ಬರ',
    'yield.predict': 'ಇಳುವರಿ ಮುನ್ಸೂಚಿಸಿ',
    'yield.predicting': 'ಮುನ್ಸೂಚಿಸಲಾಗುತ್ತಿದೆ...',
    'yield.results': 'ಮುನ್ಸೂಚನೆ ಫಲಿತಾಂಶಗಳು',
    'yield.estimatedYield': 'ಅಂದಾಜು ಇಳುವರಿ',
    'yield.revenue': 'ನಿರೀಕ್ಷಿತ ಆದಾಯ',
    'yield.harvestDays': 'ಕೊಯ್ಲಿಗೆ ದಿನಗಳು',
    
    // Market Prices
    'market.title': 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳು',
    'market.subtitle': 'ಕೃಷಿ ಸರಕುಗಳ ರಿಯಲ್-ಟೈಮ್ ಬೆಲೆಗಳು',
    'market.search': 'ಬೆಳೆಗಳನ್ನು ಹುಡುಕಿ...',
    'market.filter': 'ಮಾರುಕಟ್ಟೆಯಿಂದ ಫಿಲ್ಟರ್ ಮಾಡಿ',
    'market.allMarkets': 'ಎಲ್ಲಾ ಮಾರುಕಟ್ಟೆಗಳು',
    'market.crop': 'ಬೆಳೆ',
    'market.variety': 'ತಳಿ',
    'market.price': 'ಬೆಲೆ (₹/ಕ್ವಿಂಟಲ್)',
    'market.trend': 'ಪ್ರವೃತ್ತಿ',
    'market.location': 'ಸ್ಥಳ',
    
    // Nearby Markets
    'nearby.title': 'ಹತ್ತಿರದ ಮಾರುಕಟ್ಟೆಗಳು',
    'nearby.subtitle': 'ನಿಮ್ಮ ಸ್ಥಳದ ಬಳಿ ಕೃಷಿ ಮಾರುಕಟ್ಟೆಗಳನ್ನು ಹುಡುಕಿ',
    'nearby.search': 'ಮಾರುಕಟ್ಟೆಗಳನ್ನು ಹುಡುಕಿ...',
    'nearby.call': 'ಕರೆ ಮಾಡಿ',
    'nearby.directions': 'ದಿಕ್ಕುಗಳನ್ನು ಪಡೆಯಿರಿ',
    'nearby.crops': 'ಲಭ್ಯವಿರುವ ಬೆಳೆಗಳು',
    'nearby.hours': 'ತೆರೆಯುವ ಸಮಯ',
    'nearby.rating': 'ರೇಟಿಂಗ್',
    
    // Policies
    'policies.title': 'ಸರ್ಕಾರಿ ನೀತಿಗಳು ಮತ್ತು ಯೋಜನೆಗಳು',
    'policies.subtitle': 'ಇತ್ತೀಚಿನ ಕೃಷಿ ನೀತಿಗಳ ಬಗ್ಗೆ ನವೀಕೃತವಾಗಿರಿ',
    'policies.search': 'ನೀತಿಗಳನ್ನು ಹುಡುಕಿ...',
    'policies.all': 'ಎಲ್ಲಾ',
    'policies.subsidy': 'ಸಬ್ಸಿಡಿ',
    'policies.insurance': 'ವಿಮೆ',
    'policies.loan': 'ಸಾಲ',
    'policies.support': 'ಬೆಂಬಲ',
    'policies.readMore': 'ಇನ್ನಷ್ಟು ಓದಿ',
    
    // Auth
    'auth.login': 'ಲಾಗಿನ್',
    'auth.signup': 'ಸೈನ್ ಅಪ್',
    'auth.email': 'ಇಮೇಲ್',
    'auth.password': 'ಪಾಸ್‌ವರ್ಡ್',
    'auth.fullName': 'ಪೂರ್ಣ ಹೆಸರು',
    'auth.phone': 'ಫೋನ್ ನಂಬರ್',
    'auth.village': 'ಹಳ್ಳಿ/ನಗರ',
    'auth.role': 'ನಾನು',
    'auth.farmer': 'ರೈತ',
    'auth.dealer': 'ವ್ಯಾಪಾರಿ',
    'auth.loginButton': 'ಲಾಗಿನ್ ಮಾಡಿ',
    'auth.signupButton': 'ಖಾತೆ ರಚಿಸಿ',
    'auth.noAccount': 'ಖಾತೆ ಇಲ್ಲವೇ?',
    'auth.hasAccount': 'ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?',
    
    // Chat
    'chat.title': 'FarmGenius AI',
    'chat.placeholder': 'ಕೃಷಿ ಬಗ್ಗೆ ಕೇಳಿ...',
    'chat.send': 'ಕಳುಹಿಸಿ',
    'chat.greeting': 'ನಮಸ್ಕಾರ! ನಾನು ನಿಮ್ಮ AI ಕೃಷಿ ಸಹಾಯಕ. ಇಂದು ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
    
    // Footer
    'footer.quickLinks': 'ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು',
    'footer.helpSupport': 'ಸಹಾಯ ಮತ್ತು ಬೆಂಬಲ',
    'footer.contactUs': 'ಸಂಪರ್ಕಿಸಿ',
    'footer.faq': 'FAQ',
    'footer.tutorials': 'ಟ್ಯುಟೋರಿಯಲ್‌ಗಳು',
    'footer.feedback': 'ಪ್ರತಿಕ್ರಿಯೆ',
    'footer.privacy': 'ಗೌಪ್ಯತಾ ನೀತಿ',
    'footer.terms': 'ಸೇವಾ ನಿಯಮಗಳು',
    'footer.rights': 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
    'footer.tagline': 'ಉತ್ತಮ ಬೆಳೆ ನಿರ್ವಹಣೆ, ರೋಗ ಪತ್ತೆ ಮತ್ತು ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿಗಾಗಿ AI-ಆಧಾರಿತ ಒಳನೋಟಗಳೊಂದಿಗೆ ರೈತರನ್ನು ಸಬಲೀಕರಿಸುವುದು.',
    
    // Stats
    'stats.farmersHelped': 'ರೈತರಿಗೆ ಸಹಾಯ ಮಾಡಲಾಗಿದೆ',
    'stats.accuracy': 'ಪತ್ತೆ ನಿಖರತೆ',
    'stats.marketsListed': 'ಮಾರುಕಟ್ಟೆಗಳು ಪಟ್ಟಿಮಾಡಲಾಗಿದೆ',
    'stats.aiSupport': 'AI ಬೆಂಬಲ',
    
    // Benefits
    'benefits.title': 'ರೈತರು ಏಕೆ FarmGenius ಆಯ್ಕೆ ಮಾಡುತ್ತಾರೆ',
    'benefits.subtitle': 'ಈಗಾಗಲೇ AI ಬಳಸಿ ತಮ್ಮ ಬೆಳೆ ಇಳುವರಿಯನ್ನು ಸುಧಾರಿಸುತ್ತಿರುವ ಸಾವಿರಾರು ರೈತರೊಂದಿಗೆ ಸೇರಿ.',
    'benefits.free': 'ಎಲ್ಲಾ ರೈತರಿಗೆ ಉಚಿತ',
    'benefits.languages': 'ಹಲವು ಭಾರತೀಯ ಭಾಷೆಗಳಲ್ಲಿ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
    'benefits.noExpertise': 'ತಾಂತ್ರಿಕ ಪರಿಣತಿ ಅಗತ್ಯವಿಲ್ಲ',
    'benefits.experts': 'ಕೃಷಿ ತಜ್ಞರ ಬೆಂಬಲ',
    'benefits.updates': 'ಹೊಸ ವೈಶಿಷ್ಟ್ಯಗಳೊಂದಿಗೆ ನಿಯಮಿತ ನವೀಕರಣಗಳು',
    'benefits.community': 'ಸಮುದಾಯ ಬೆಂಬಲ ಮತ್ತು ವೇದಿಕೆಗಳು',
    'benefits.startButton': 'FarmGenius ಬಳಸಲು ಪ್ರಾರಂಭಿಸಿ',
    'benefits.smartAg': 'ಸ್ಮಾರ್ಟ್ ಕೃಷಿ',
    'benefits.poweredByAI': 'AI ಆಧಾರಿತ',
    
    // Hero badge
    'landing.hero.badge': 'AI-ಆಧಾರಿತ ಕೃಷಿ ಪರಿಹಾರಗಳು',
    'common.error': 'ದೋಷ ಸಂಭವಿಸಿದೆ',
    'common.save': 'ಉಳಿಸಿ',
    'common.cancel': 'ರದ್ದುಮಾಡಿ',
    'common.delete': 'ಅಳಿಸಿ',
    'common.edit': 'ಸಂಪಾದಿಸಿ',
    'common.view': 'ನೋಡಿ',
    'common.back': 'ಹಿಂದೆ',
    'common.next': 'ಮುಂದೆ',
    'common.submit': 'ಸಲ್ಲಿಸಿ',
    'common.search': 'ಹುಡುಕಿ',
    
    // Profile
    'profile.title': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
    'profile.subtitle': 'ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ಮಾಹಿತಿಯನ್ನು ನವೀಕರಿಸಿ',
    'profile.email': 'ಇಮೇಲ್',
    'profile.emailHint': 'ಇಮೇಲ್ ಬದಲಾಯಿಸಲು ಸಾಧ್ಯವಿಲ್ಲ',
    'profile.fullName': 'ಪೂರ್ಣ ಹೆಸರು',
    'profile.fullNamePlaceholder': 'ನಿಮ್ಮ ಪೂರ್ಣ ಹೆಸರನ್ನು ನಮೂದಿಸಿ',
    'profile.phone': 'ಫೋನ್ ನಂಬರ್',
    'profile.phonePlaceholder': 'ನಿಮ್ಮ ಫೋನ್ ನಂಬರ್ ನಮೂದಿಸಿ',
    'profile.village': 'ಹಳ್ಳಿ/ನಗರ',
    'profile.villagePlaceholder': 'ನಿಮ್ಮ ಹಳ್ಳಿ ಅಥವಾ ನಗರವನ್ನು ನಮೂದಿಸಿ',
    'profile.save': 'ಬದಲಾವಣೆಗಳನ್ನು ಉಳಿಸಿ',
    'profile.saving': 'ಉಳಿಸಲಾಗುತ್ತಿದೆ...',
    'profile.success': 'ಪ್ರೊಫೈಲ್ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!',
    'profile.error': 'ಪ್ರೊಫೈಲ್ ನವೀಕರಿಸಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    'profile.changePhoto': 'ಫೋಟೋ ಬದಲಾಯಿಸಿ',
    'profile.uploadingPhoto': 'ಅಪ್‌ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    'profile.photoSuccess': 'ಫೋಟೋ ಯಶಸ್ವಿಯಾಗಿ ನವೀಕರಿಸಲಾಗಿದೆ!',
    'profile.photoError': 'ಫೋಟೋ ಅಪ್‌ಲೋಡ್ ಮಾಡಲು ವಿಫಲವಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    
    // Dealer
    'dealer.dashboard': 'ವ್ಯಾಪಾರಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    'dealer.welcome': 'ಸ್ವಾಗತ',
    'dealer.subtitle': 'ನಿಮ್ಮ ವ್ಯಾಪಾರಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್‌ನಿಂದ ವ್ಯಾಪಾರ ಕಾರ್ಯಾಚರಣೆಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'dealer.buyOffers': 'ಖರೀದಿ ಆಫರ್‌ಗಳು',
    'dealer.buyOffersDesc': 'ನಿಮ್ಮ ಬಯಸಿದ ಬೆಲೆಗೆ ರೈತರಿಂದ ಬೆಳೆಗಳನ್ನು ಖರೀದಿಸಲು ಆಫರ್‌ಗಳನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿ',
    'dealer.farmerDirectory': 'ರೈತ ಡೈರೆಕ್ಟರಿ',
    'dealer.farmerDirectoryDesc': 'ನಿಮ್ಮ ಪ್ರದೇಶದ ರೈತರನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ ಮತ್ತು ಸಂಪರ್ಕಿಸಿ',
    'dealer.inventory': 'ದಾಸ್ತಾನು',
    'dealer.inventoryDesc': 'ಖರೀದಿಸಿದ ಬೆಳೆಗಳನ್ನು ಟ್ರ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ನಿಮ್ಮ ಸ್ಟಾಕ್ ನಿರ್ವಹಿಸಿ',
    'dealer.orders': 'ಆದೇಶಗಳು',
    'dealer.ordersDesc': 'ಆದೇಶಗಳು, ವಿತರಣೆಗಳು ಮತ್ತು ಪಾವತಿಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    'dealer.activeOffers': 'ಸಕ್ರಿಯ ಆಫರ್‌ಗಳು',
    'dealer.quintalsInStock': 'ಸ್ಟಾಕ್‌ನಲ್ಲಿ ಕ್ವಿಂಟಾಲ್',
    'dealer.pendingOrders': 'ಬಾಕಿ ಇರುವ ಆದೇಶಗಳು',
    'dealer.completed': 'ಪೂರ್ಣಗೊಂಡಿದೆ',
    'dealer.quickActions': 'ತ್ವರಿತ ಕ್ರಿಯೆಗಳು',
    'dealer.postNewOffer': 'ಹೊಸ ಖರೀದಿ ಆಫರ್ ಪೋಸ್ಟ್ ಮಾಡಿ',
    'dealer.addInventory': 'ದಾಸ್ತಾನು ಸೇರಿಸಿ',
    'dealer.checkPrices': 'ಮಾರುಕಟ್ಟೆ ಬೆಲೆಗಳನ್ನು ಪರಿಶೀಲಿಸಿ',
    'dealer.newOffer': 'ಹೊಸ ಆಫರ್',
    'dealer.createOffer': 'ಖರೀದಿ ಆಫರ್ ರಚಿಸಿ',
    'dealer.editOffer': 'ಆಫರ್ ಸಂಪಾದಿಸಿ',
    'dealer.crop': 'ಬೆಳೆ',
    'dealer.variety': 'ವಿಧ',
    'dealer.quantity': 'ಪ್ರಮಾಣ (ಕ್ವಿಂಟಾಲ್)',
    'dealer.pricePerQuintal': 'ಬೆಲೆ (₹/ಕ್ವಿಂಟಾಲ್)',
    'dealer.location': 'ಸ್ಥಳ',
    'dealer.description': 'ವಿವರಣೆ',
    'dealer.status': 'ಸ್ಥಿತಿ',
    'dealer.active': 'ಸಕ್ರಿಯ',
    'dealer.closed': 'ಮುಚ್ಚಲಾಗಿದೆ',
    'dealer.expired': 'ಅವಧಿ ಮುಗಿದಿದೆ',
    'dealer.closeOffer': 'ಆಫರ್ ಮುಚ್ಚಿ',
    'dealer.reactivate': 'ಮತ್ತೆ ಸಕ್ರಿಯಗೊಳಿಸಿ',
    'dealer.noOffers': 'ಯಾವುದೇ ಖರೀದಿ ಆಫರ್‌ಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    'dealer.createFirst': 'ನಿಮ್ಮ ಮೊದಲ ಆಫರ್ ರಚಿಸಿ',
    'dealer.browseFarmers': 'ರೈತರನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
    'dealer.searchFarmers': 'ಹೆಸರು ಅಥವಾ ಸ್ಥಳದಿಂದ ರೈತರನ್ನು ಹುಡುಕಿ...',
    'dealer.noFarmers': 'ಯಾವುದೇ ರೈತರು ಕಂಡುಬಂದಿಲ್ಲ',
    'dealer.contact': 'ಸಂಪರ್ಕ',
    'dealer.call': 'ಕರೆ ಮಾಡಿ',
    'dealer.addToInventory': 'ದಾಸ್ತಾನಿಗೆ ಸೇರಿಸಿ',
    'dealer.farmerName': 'ರೈತರ ಹೆಸರು',
    'dealer.purchaseDate': 'ಖರೀದಿ ದಿನಾಂಕ',
    'dealer.purchasePrice': 'ಖರೀದಿ ಬೆಲೆ',
    'dealer.notes': 'ಟಿಪ್ಪಣಿಗಳು',
    'dealer.noInventory': 'ಯಾವುದೇ ದಾಸ್ತಾನು ಐಟಂಗಳಿಲ್ಲ',
    'dealer.createOrder': 'ಆದೇಶ ರಚಿಸಿ',
    'dealer.orderDetails': 'ಆದೇಶ ವಿವರಗಳು',
    'dealer.totalAmount': 'ಒಟ್ಟು ಮೊತ್ತ',
    'dealer.paymentStatus': 'ಪಾವತಿ ಸ್ಥಿತಿ',
    'dealer.deliveryAddress': 'ವಿತರಣಾ ವಿಳಾಸ',
    'dealer.pending': 'ಬಾಕಿ ಇದೆ',
    'dealer.confirmed': 'ದೃಢೀಕರಿಸಲಾಗಿದೆ',
    'dealer.shipped': 'ಕಳುಹಿಸಲಾಗಿದೆ',
    'dealer.delivered': 'ವಿತರಿಸಲಾಗಿದೆ',
    'dealer.cancelled': 'ರದ್ದುಪಡಿಸಲಾಗಿದೆ',
    'dealer.paid': 'ಪಾವತಿಸಲಾಗಿದೆ',
    'dealer.unpaid': 'ಪಾವತಿಸಿಲ್ಲ',
    'dealer.noOrders': 'ಯಾವುದೇ ಆದೇಶಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    
    // Voice
    'voice.tapToSpeak': 'ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ',
    'voice.voiceNav': 'ಧ್ವನಿ',
    'voice.navigating': 'ನ್ಯಾವಿಗೇಟ್ ಆಗುತ್ತಿದೆ...',
    'voice.notUnderstood': 'ಆಜ್ಞೆ ಅರ್ಥವಾಗಲಿಲ್ಲ',
    'voice.error': 'ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆ ದೋಷ',
    'voice.errorDesc': 'ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ ಅಥವಾ ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿ ಪರಿಶೀಲಿಸಿ',
    'voice.notSupported': 'ಧ್ವನಿ ಬೆಂಬಲಿಸಲಾಗಿಲ್ಲ',
    'voice.notSupportedDesc': 'ನಿಮ್ಮ ಬ್ರೌಸರ್ ಧ್ವನಿ ಗುರುತಿಸುವಿಕೆಯನ್ನು ಬೆಂಬಲಿಸುವುದಿಲ್ಲ',
    'voice.listen': 'ಆಲಿಸಿ',
    'voice.stop': 'ನಿಲ್ಲಿಸಿ',
    'voice.listening': 'ಆಲಿಸುತ್ತಿದೆ...',
    'voice.startListening': 'ಧ್ವನಿ ಇನ್‌ಪುಟ್ ಪ್ರಾರಂಭಿಸಿ',
    'voice.stopListening': 'ಧ್ವನಿ ಇನ್‌ಪುಟ್ ನಿಲ್ಲಿಸಿ',
    'voice.speakResults': 'ಫಲಿತಾಂಶಗಳನ್ನು ಆಲಿಸಿ',
    
    // Chatbot
    'chatbot.subtitle': 'ನಿಮ್ಮ ಕೃಷಿ ಸಹಾಯಕ',
    'chatbot.placeholder': 'ಬೆಳೆ, ರೋಗ, ಬೆಲೆ ಬಗ್ಗೆ ಕೇಳಿ...',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('farmgenius-language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('farmgenius-language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
